// Code generated by Fern. DO NOT EDIT.

package balance

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve the current account balance for a specific currency.
func (c *Client) GetBalance(
	ctx context.Context,
	request *vobiz.GetBalanceRequest,
	opts ...option.RequestOption,
) (*vobiz.GetBalanceResponse, error) {
	response, err := c.WithRawResponse.GetBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve paginated transaction history for the account.
func (c *Client) ListTransactions(
	ctx context.Context,
	request *vobiz.ListTransactionsRequest,
	opts ...option.RequestOption,
) (*vobiz.ListTransactionsResponse, error) {
	response, err := c.WithRawResponse.ListTransactions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
