// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	big "math/big"
)

var (
	getConcurrencyRequestFieldAuthID = big.NewInt(1 << 0)
)

type GetConcurrencyRequest struct {
	// Your account Auth ID
	AuthID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetConcurrencyRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyRequest) SetAuthID(authID string) {
	g.AuthID = authID
	g.require(getConcurrencyRequestFieldAuthID)
}

var (
	getConcurrencyResponseFieldAccountID       = big.NewInt(1 << 0)
	getConcurrencyResponseFieldConcurrentCalls = big.NewInt(1 << 1)
	getConcurrencyResponseFieldMaxConcurrent   = big.NewInt(1 << 2)
	getConcurrencyResponseFieldUtilizationPct  = big.NewInt(1 << 3)
	getConcurrencyResponseFieldRequestID       = big.NewInt(1 << 4)
)

type GetConcurrencyResponse struct {
	AccountID       string `json:"account_id" url:"account_id"`
	ConcurrentCalls int    `json:"concurrent_calls" url:"concurrent_calls"`
	MaxConcurrent   int    `json:"max_concurrent" url:"max_concurrent"`
	UtilizationPct  int    `json:"utilization_pct" url:"utilization_pct"`
	RequestID       string `json:"request_id" url:"request_id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetConcurrencyResponse) GetAccountID() string {
	if g == nil {
		return ""
	}
	return g.AccountID
}

func (g *GetConcurrencyResponse) GetConcurrentCalls() int {
	if g == nil {
		return 0
	}
	return g.ConcurrentCalls
}

func (g *GetConcurrencyResponse) GetMaxConcurrent() int {
	if g == nil {
		return 0
	}
	return g.MaxConcurrent
}

func (g *GetConcurrencyResponse) GetUtilizationPct() int {
	if g == nil {
		return 0
	}
	return g.UtilizationPct
}

func (g *GetConcurrencyResponse) GetRequestID() string {
	if g == nil {
		return ""
	}
	return g.RequestID
}

func (g *GetConcurrencyResponse) GetExtraProperties() map[string]interface{} {
	if g == nil {
		return nil
	}
	return g.extraProperties
}

func (g *GetConcurrencyResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccountID sets the AccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyResponse) SetAccountID(accountID string) {
	g.AccountID = accountID
	g.require(getConcurrencyResponseFieldAccountID)
}

// SetConcurrentCalls sets the ConcurrentCalls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyResponse) SetConcurrentCalls(concurrentCalls int) {
	g.ConcurrentCalls = concurrentCalls
	g.require(getConcurrencyResponseFieldConcurrentCalls)
}

// SetMaxConcurrent sets the MaxConcurrent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyResponse) SetMaxConcurrent(maxConcurrent int) {
	g.MaxConcurrent = maxConcurrent
	g.require(getConcurrencyResponseFieldMaxConcurrent)
}

// SetUtilizationPct sets the UtilizationPct field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyResponse) SetUtilizationPct(utilizationPct int) {
	g.UtilizationPct = utilizationPct
	g.require(getConcurrencyResponseFieldUtilizationPct)
}

// SetRequestID sets the RequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetConcurrencyResponse) SetRequestID(requestID string) {
	g.RequestID = requestID
	g.require(getConcurrencyResponseFieldRequestID)
}

func (g *GetConcurrencyResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetConcurrencyResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetConcurrencyResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetConcurrencyResponse) MarshalJSON() ([]byte, error) {
	type embed GetConcurrencyResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetConcurrencyResponse) String() string {
	if g == nil {
		return "<nil>"
	}
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	retrieveAccountResponseFieldType                     = big.NewInt(1 << 0)
	retrieveAccountResponseFieldID                       = big.NewInt(1 << 1)
	retrieveAccountResponseFieldApiId                    = big.NewInt(1 << 2)
	retrieveAccountResponseFieldName                     = big.NewInt(1 << 3)
	retrieveAccountResponseFieldEmail                    = big.NewInt(1 << 4)
	retrieveAccountResponseFieldPhone                    = big.NewInt(1 << 5)
	retrieveAccountResponseFieldDescription              = big.NewInt(1 << 6)
	retrieveAccountResponseFieldAuthID                   = big.NewInt(1 << 7)
	retrieveAccountResponseFieldAuthSecret               = big.NewInt(1 << 8)
	retrieveAccountResponseFieldAuthTokenExpireTime      = big.NewInt(1 << 9)
	retrieveAccountResponseFieldCountry                  = big.NewInt(1 << 10)
	retrieveAccountResponseFieldTimezone                 = big.NewInt(1 << 11)
	retrieveAccountResponseFieldCity                     = big.NewInt(1 << 12)
	retrieveAccountResponseFieldState                    = big.NewInt(1 << 13)
	retrieveAccountResponseFieldAddress                  = big.NewInt(1 << 14)
	retrieveAccountResponseFieldZipCode                  = big.NewInt(1 << 15)
	retrieveAccountResponseFieldCompany                  = big.NewInt(1 << 16)
	retrieveAccountResponseFieldAccountType              = big.NewInt(1 << 17)
	retrieveAccountResponseFieldPostpaid                 = big.NewInt(1 << 18)
	retrieveAccountResponseFieldAutoRecharge             = big.NewInt(1 << 19)
	retrieveAccountResponseFieldAutoRechargeConfig       = big.NewInt(1 << 20)
	retrieveAccountResponseFieldEnabled                  = big.NewInt(1 << 21)
	retrieveAccountResponseFieldCarrierType              = big.NewInt(1 << 22)
	retrieveAccountResponseFieldCustomerType             = big.NewInt(1 << 23)
	retrieveAccountResponseFieldCreditLimit              = big.NewInt(1 << 24)
	retrieveAccountResponseFieldCpsLimit                 = big.NewInt(1 << 25)
	retrieveAccountResponseFieldConcurrentCallsLimit     = big.NewInt(1 << 26)
	retrieveAccountResponseFieldBaseCpsLimit             = big.NewInt(1 << 27)
	retrieveAccountResponseFieldBaseConcurrentCallsLimit = big.NewInt(1 << 28)
	retrieveAccountResponseFieldPurchasedCps             = big.NewInt(1 << 29)
	retrieveAccountResponseFieldPurchasedConcurrentCalls = big.NewInt(1 << 30)
	retrieveAccountResponseFieldRiskRating               = big.NewInt(1 << 31)
	retrieveAccountResponseFieldRiskStatus               = big.NewInt(1 << 32)
	retrieveAccountResponseFieldFeatures                 = big.NewInt(1 << 33)
	retrieveAccountResponseFieldIPAuthEnabled            = big.NewInt(1 << 34)
	retrieveAccountResponseFieldIPWhitelistRules         = big.NewInt(1 << 35)
	retrieveAccountResponseFieldAllowAwsIps              = big.NewInt(1 << 36)
	retrieveAccountResponseFieldRole                     = big.NewInt(1 << 37)
	retrieveAccountResponseFieldIsActive                 = big.NewInt(1 << 38)
	retrieveAccountResponseFieldIsVerified               = big.NewInt(1 << 39)
	retrieveAccountResponseFieldIsTrialAccount           = big.NewInt(1 << 40)
	retrieveAccountResponseFieldCreatedAt                = big.NewInt(1 << 41)
	retrieveAccountResponseFieldUpdatedAt                = big.NewInt(1 << 42)
	retrieveAccountResponseFieldLastLogin                = big.NewInt(1 << 43)
	retrieveAccountResponseFieldPricingTierID            = big.NewInt(1 << 44)
	retrieveAccountResponseFieldPricingTier              = big.NewInt(1 << 45)
)

type RetrieveAccountResponse struct {
	Type                     string                              `json:"type" url:"type"`
	ID                       string                              `json:"id" url:"id"`
	ApiId                    string                              `json:"api_id" url:"api_id"`
	Name                     string                              `json:"name" url:"name"`
	Email                    string                              `json:"email" url:"email"`
	Phone                    string                              `json:"phone" url:"phone"`
	Description              string                              `json:"description" url:"description"`
	AuthID                   string                              `json:"auth_id" url:"auth_id"`
	AuthSecret               string                              `json:"auth_secret" url:"auth_secret"`
	AuthTokenExpireTime      any                                 `json:"auth_token_expire_time,omitempty" url:"auth_token_expire_time,omitempty"`
	Country                  string                              `json:"country" url:"country"`
	Timezone                 string                              `json:"timezone" url:"timezone"`
	City                     string                              `json:"city" url:"city"`
	State                    string                              `json:"state" url:"state"`
	Address                  string                              `json:"address" url:"address"`
	ZipCode                  string                              `json:"zip_code" url:"zip_code"`
	Company                  string                              `json:"company" url:"company"`
	AccountType              string                              `json:"account_type" url:"account_type"`
	Postpaid                 bool                                `json:"postpaid" url:"postpaid"`
	AutoRecharge             bool                                `json:"auto_recharge" url:"auto_recharge"`
	AutoRechargeConfig       any                                 `json:"auto_recharge_config,omitempty" url:"auto_recharge_config,omitempty"`
	Enabled                  bool                                `json:"enabled" url:"enabled"`
	CarrierType              any                                 `json:"carrier_type,omitempty" url:"carrier_type,omitempty"`
	CustomerType             any                                 `json:"customer_type,omitempty" url:"customer_type,omitempty"`
	CreditLimit              int                                 `json:"credit_limit" url:"credit_limit"`
	CpsLimit                 int                                 `json:"cps_limit" url:"cps_limit"`
	ConcurrentCallsLimit     int                                 `json:"concurrent_calls_limit" url:"concurrent_calls_limit"`
	BaseCpsLimit             int                                 `json:"base_cps_limit" url:"base_cps_limit"`
	BaseConcurrentCallsLimit int                                 `json:"base_concurrent_calls_limit" url:"base_concurrent_calls_limit"`
	PurchasedCps             int                                 `json:"purchased_cps" url:"purchased_cps"`
	PurchasedConcurrentCalls int                                 `json:"purchased_concurrent_calls" url:"purchased_concurrent_calls"`
	RiskRating               int                                 `json:"risk_rating" url:"risk_rating"`
	RiskStatus               any                                 `json:"risk_status,omitempty" url:"risk_status,omitempty"`
	Features                 *RetrieveAccountResponseFeatures    `json:"features" url:"features"`
	IPAuthEnabled            bool                                `json:"ip_auth_enabled" url:"ip_auth_enabled"`
	IPWhitelistRules         map[string]any                      `json:"ip_whitelist_rules" url:"ip_whitelist_rules"`
	AllowAwsIps              bool                                `json:"allow_aws_ips" url:"allow_aws_ips"`
	Role                     string                              `json:"role" url:"role"`
	IsActive                 bool                                `json:"is_active" url:"is_active"`
	IsVerified               bool                                `json:"is_verified" url:"is_verified"`
	IsTrialAccount           bool                                `json:"is_trial_account" url:"is_trial_account"`
	CreatedAt                string                              `json:"created_at" url:"created_at"`
	UpdatedAt                string                              `json:"updated_at" url:"updated_at"`
	LastLogin                string                              `json:"last_login" url:"last_login"`
	PricingTierID            string                              `json:"pricing_tier_id" url:"pricing_tier_id"`
	PricingTier              *RetrieveAccountResponsePricingTier `json:"pricing_tier" url:"pricing_tier"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveAccountResponse) GetType() string {
	if r == nil {
		return ""
	}
	return r.Type
}

func (r *RetrieveAccountResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RetrieveAccountResponse) GetApiId() string {
	if r == nil {
		return ""
	}
	return r.ApiId
}

func (r *RetrieveAccountResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RetrieveAccountResponse) GetEmail() string {
	if r == nil {
		return ""
	}
	return r.Email
}

func (r *RetrieveAccountResponse) GetPhone() string {
	if r == nil {
		return ""
	}
	return r.Phone
}

func (r *RetrieveAccountResponse) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RetrieveAccountResponse) GetAuthID() string {
	if r == nil {
		return ""
	}
	return r.AuthID
}

func (r *RetrieveAccountResponse) GetAuthSecret() string {
	if r == nil {
		return ""
	}
	return r.AuthSecret
}

func (r *RetrieveAccountResponse) GetAuthTokenExpireTime() any {
	if r == nil {
		return nil
	}
	return r.AuthTokenExpireTime
}

func (r *RetrieveAccountResponse) GetCountry() string {
	if r == nil {
		return ""
	}
	return r.Country
}

func (r *RetrieveAccountResponse) GetTimezone() string {
	if r == nil {
		return ""
	}
	return r.Timezone
}

func (r *RetrieveAccountResponse) GetCity() string {
	if r == nil {
		return ""
	}
	return r.City
}

func (r *RetrieveAccountResponse) GetState() string {
	if r == nil {
		return ""
	}
	return r.State
}

func (r *RetrieveAccountResponse) GetAddress() string {
	if r == nil {
		return ""
	}
	return r.Address
}

func (r *RetrieveAccountResponse) GetZipCode() string {
	if r == nil {
		return ""
	}
	return r.ZipCode
}

func (r *RetrieveAccountResponse) GetCompany() string {
	if r == nil {
		return ""
	}
	return r.Company
}

func (r *RetrieveAccountResponse) GetAccountType() string {
	if r == nil {
		return ""
	}
	return r.AccountType
}

func (r *RetrieveAccountResponse) GetPostpaid() bool {
	if r == nil {
		return false
	}
	return r.Postpaid
}

func (r *RetrieveAccountResponse) GetAutoRecharge() bool {
	if r == nil {
		return false
	}
	return r.AutoRecharge
}

func (r *RetrieveAccountResponse) GetAutoRechargeConfig() any {
	if r == nil {
		return nil
	}
	return r.AutoRechargeConfig
}

func (r *RetrieveAccountResponse) GetEnabled() bool {
	if r == nil {
		return false
	}
	return r.Enabled
}

func (r *RetrieveAccountResponse) GetCarrierType() any {
	if r == nil {
		return nil
	}
	return r.CarrierType
}

func (r *RetrieveAccountResponse) GetCustomerType() any {
	if r == nil {
		return nil
	}
	return r.CustomerType
}

func (r *RetrieveAccountResponse) GetCreditLimit() int {
	if r == nil {
		return 0
	}
	return r.CreditLimit
}

func (r *RetrieveAccountResponse) GetCpsLimit() int {
	if r == nil {
		return 0
	}
	return r.CpsLimit
}

func (r *RetrieveAccountResponse) GetConcurrentCallsLimit() int {
	if r == nil {
		return 0
	}
	return r.ConcurrentCallsLimit
}

func (r *RetrieveAccountResponse) GetBaseCpsLimit() int {
	if r == nil {
		return 0
	}
	return r.BaseCpsLimit
}

func (r *RetrieveAccountResponse) GetBaseConcurrentCallsLimit() int {
	if r == nil {
		return 0
	}
	return r.BaseConcurrentCallsLimit
}

func (r *RetrieveAccountResponse) GetPurchasedCps() int {
	if r == nil {
		return 0
	}
	return r.PurchasedCps
}

func (r *RetrieveAccountResponse) GetPurchasedConcurrentCalls() int {
	if r == nil {
		return 0
	}
	return r.PurchasedConcurrentCalls
}

func (r *RetrieveAccountResponse) GetRiskRating() int {
	if r == nil {
		return 0
	}
	return r.RiskRating
}

func (r *RetrieveAccountResponse) GetRiskStatus() any {
	if r == nil {
		return nil
	}
	return r.RiskStatus
}

func (r *RetrieveAccountResponse) GetFeatures() *RetrieveAccountResponseFeatures {
	if r == nil {
		return nil
	}
	return r.Features
}

func (r *RetrieveAccountResponse) GetIPAuthEnabled() bool {
	if r == nil {
		return false
	}
	return r.IPAuthEnabled
}

func (r *RetrieveAccountResponse) GetIPWhitelistRules() map[string]any {
	if r == nil {
		return nil
	}
	return r.IPWhitelistRules
}

func (r *RetrieveAccountResponse) GetAllowAwsIps() bool {
	if r == nil {
		return false
	}
	return r.AllowAwsIps
}

func (r *RetrieveAccountResponse) GetRole() string {
	if r == nil {
		return ""
	}
	return r.Role
}

func (r *RetrieveAccountResponse) GetIsActive() bool {
	if r == nil {
		return false
	}
	return r.IsActive
}

func (r *RetrieveAccountResponse) GetIsVerified() bool {
	if r == nil {
		return false
	}
	return r.IsVerified
}

func (r *RetrieveAccountResponse) GetIsTrialAccount() bool {
	if r == nil {
		return false
	}
	return r.IsTrialAccount
}

func (r *RetrieveAccountResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RetrieveAccountResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RetrieveAccountResponse) GetLastLogin() string {
	if r == nil {
		return ""
	}
	return r.LastLogin
}

func (r *RetrieveAccountResponse) GetPricingTierID() string {
	if r == nil {
		return ""
	}
	return r.PricingTierID
}

func (r *RetrieveAccountResponse) GetPricingTier() *RetrieveAccountResponsePricingTier {
	if r == nil {
		return nil
	}
	return r.PricingTier
}

func (r *RetrieveAccountResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RetrieveAccountResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetType(type_ string) {
	r.Type = type_
	r.require(retrieveAccountResponseFieldType)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetID(id string) {
	r.ID = id
	r.require(retrieveAccountResponseFieldID)
}

// SetApiId sets the ApiId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetApiId(apiId string) {
	r.ApiId = apiId
	r.require(retrieveAccountResponseFieldApiId)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetName(name string) {
	r.Name = name
	r.require(retrieveAccountResponseFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetEmail(email string) {
	r.Email = email
	r.require(retrieveAccountResponseFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPhone(phone string) {
	r.Phone = phone
	r.require(retrieveAccountResponseFieldPhone)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetDescription(description string) {
	r.Description = description
	r.require(retrieveAccountResponseFieldDescription)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAuthID(authID string) {
	r.AuthID = authID
	r.require(retrieveAccountResponseFieldAuthID)
}

// SetAuthSecret sets the AuthSecret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAuthSecret(authSecret string) {
	r.AuthSecret = authSecret
	r.require(retrieveAccountResponseFieldAuthSecret)
}

// SetAuthTokenExpireTime sets the AuthTokenExpireTime field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAuthTokenExpireTime(authTokenExpireTime any) {
	r.AuthTokenExpireTime = authTokenExpireTime
	r.require(retrieveAccountResponseFieldAuthTokenExpireTime)
}

// SetCountry sets the Country field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCountry(country string) {
	r.Country = country
	r.require(retrieveAccountResponseFieldCountry)
}

// SetTimezone sets the Timezone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetTimezone(timezone string) {
	r.Timezone = timezone
	r.require(retrieveAccountResponseFieldTimezone)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCity(city string) {
	r.City = city
	r.require(retrieveAccountResponseFieldCity)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetState(state string) {
	r.State = state
	r.require(retrieveAccountResponseFieldState)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAddress(address string) {
	r.Address = address
	r.require(retrieveAccountResponseFieldAddress)
}

// SetZipCode sets the ZipCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetZipCode(zipCode string) {
	r.ZipCode = zipCode
	r.require(retrieveAccountResponseFieldZipCode)
}

// SetCompany sets the Company field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCompany(company string) {
	r.Company = company
	r.require(retrieveAccountResponseFieldCompany)
}

// SetAccountType sets the AccountType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAccountType(accountType string) {
	r.AccountType = accountType
	r.require(retrieveAccountResponseFieldAccountType)
}

// SetPostpaid sets the Postpaid field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPostpaid(postpaid bool) {
	r.Postpaid = postpaid
	r.require(retrieveAccountResponseFieldPostpaid)
}

// SetAutoRecharge sets the AutoRecharge field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAutoRecharge(autoRecharge bool) {
	r.AutoRecharge = autoRecharge
	r.require(retrieveAccountResponseFieldAutoRecharge)
}

// SetAutoRechargeConfig sets the AutoRechargeConfig field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAutoRechargeConfig(autoRechargeConfig any) {
	r.AutoRechargeConfig = autoRechargeConfig
	r.require(retrieveAccountResponseFieldAutoRechargeConfig)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetEnabled(enabled bool) {
	r.Enabled = enabled
	r.require(retrieveAccountResponseFieldEnabled)
}

// SetCarrierType sets the CarrierType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCarrierType(carrierType any) {
	r.CarrierType = carrierType
	r.require(retrieveAccountResponseFieldCarrierType)
}

// SetCustomerType sets the CustomerType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCustomerType(customerType any) {
	r.CustomerType = customerType
	r.require(retrieveAccountResponseFieldCustomerType)
}

// SetCreditLimit sets the CreditLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCreditLimit(creditLimit int) {
	r.CreditLimit = creditLimit
	r.require(retrieveAccountResponseFieldCreditLimit)
}

// SetCpsLimit sets the CpsLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCpsLimit(cpsLimit int) {
	r.CpsLimit = cpsLimit
	r.require(retrieveAccountResponseFieldCpsLimit)
}

// SetConcurrentCallsLimit sets the ConcurrentCallsLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetConcurrentCallsLimit(concurrentCallsLimit int) {
	r.ConcurrentCallsLimit = concurrentCallsLimit
	r.require(retrieveAccountResponseFieldConcurrentCallsLimit)
}

// SetBaseCpsLimit sets the BaseCpsLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetBaseCpsLimit(baseCpsLimit int) {
	r.BaseCpsLimit = baseCpsLimit
	r.require(retrieveAccountResponseFieldBaseCpsLimit)
}

// SetBaseConcurrentCallsLimit sets the BaseConcurrentCallsLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetBaseConcurrentCallsLimit(baseConcurrentCallsLimit int) {
	r.BaseConcurrentCallsLimit = baseConcurrentCallsLimit
	r.require(retrieveAccountResponseFieldBaseConcurrentCallsLimit)
}

// SetPurchasedCps sets the PurchasedCps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPurchasedCps(purchasedCps int) {
	r.PurchasedCps = purchasedCps
	r.require(retrieveAccountResponseFieldPurchasedCps)
}

// SetPurchasedConcurrentCalls sets the PurchasedConcurrentCalls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPurchasedConcurrentCalls(purchasedConcurrentCalls int) {
	r.PurchasedConcurrentCalls = purchasedConcurrentCalls
	r.require(retrieveAccountResponseFieldPurchasedConcurrentCalls)
}

// SetRiskRating sets the RiskRating field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetRiskRating(riskRating int) {
	r.RiskRating = riskRating
	r.require(retrieveAccountResponseFieldRiskRating)
}

// SetRiskStatus sets the RiskStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetRiskStatus(riskStatus any) {
	r.RiskStatus = riskStatus
	r.require(retrieveAccountResponseFieldRiskStatus)
}

// SetFeatures sets the Features field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetFeatures(features *RetrieveAccountResponseFeatures) {
	r.Features = features
	r.require(retrieveAccountResponseFieldFeatures)
}

// SetIPAuthEnabled sets the IPAuthEnabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetIPAuthEnabled(ipAuthEnabled bool) {
	r.IPAuthEnabled = ipAuthEnabled
	r.require(retrieveAccountResponseFieldIPAuthEnabled)
}

// SetIPWhitelistRules sets the IPWhitelistRules field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetIPWhitelistRules(ipWhitelistRules map[string]any) {
	r.IPWhitelistRules = ipWhitelistRules
	r.require(retrieveAccountResponseFieldIPWhitelistRules)
}

// SetAllowAwsIps sets the AllowAwsIps field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetAllowAwsIps(allowAwsIps bool) {
	r.AllowAwsIps = allowAwsIps
	r.require(retrieveAccountResponseFieldAllowAwsIps)
}

// SetRole sets the Role field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetRole(role string) {
	r.Role = role
	r.require(retrieveAccountResponseFieldRole)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetIsActive(isActive bool) {
	r.IsActive = isActive
	r.require(retrieveAccountResponseFieldIsActive)
}

// SetIsVerified sets the IsVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetIsVerified(isVerified bool) {
	r.IsVerified = isVerified
	r.require(retrieveAccountResponseFieldIsVerified)
}

// SetIsTrialAccount sets the IsTrialAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetIsTrialAccount(isTrialAccount bool) {
	r.IsTrialAccount = isTrialAccount
	r.require(retrieveAccountResponseFieldIsTrialAccount)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetCreatedAt(createdAt string) {
	r.CreatedAt = createdAt
	r.require(retrieveAccountResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetUpdatedAt(updatedAt string) {
	r.UpdatedAt = updatedAt
	r.require(retrieveAccountResponseFieldUpdatedAt)
}

// SetLastLogin sets the LastLogin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetLastLogin(lastLogin string) {
	r.LastLogin = lastLogin
	r.require(retrieveAccountResponseFieldLastLogin)
}

// SetPricingTierID sets the PricingTierID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPricingTierID(pricingTierID string) {
	r.PricingTierID = pricingTierID
	r.require(retrieveAccountResponseFieldPricingTierID)
}

// SetPricingTier sets the PricingTier field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponse) SetPricingTier(pricingTier *RetrieveAccountResponsePricingTier) {
	r.PricingTier = pricingTier
	r.require(retrieveAccountResponseFieldPricingTier)
}

func (r *RetrieveAccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveAccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveAccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveAccountResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveAccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveAccountResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveAccountResponseFeaturesFieldCallQueue = big.NewInt(1 << 0)
)

type RetrieveAccountResponseFeatures struct {
	CallQueue bool `json:"call_queue" url:"call_queue"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveAccountResponseFeatures) GetCallQueue() bool {
	if r == nil {
		return false
	}
	return r.CallQueue
}

func (r *RetrieveAccountResponseFeatures) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RetrieveAccountResponseFeatures) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetCallQueue sets the CallQueue field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponseFeatures) SetCallQueue(callQueue bool) {
	r.CallQueue = callQueue
	r.require(retrieveAccountResponseFeaturesFieldCallQueue)
}

func (r *RetrieveAccountResponseFeatures) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveAccountResponseFeatures
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveAccountResponseFeatures(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveAccountResponseFeatures) MarshalJSON() ([]byte, error) {
	type embed RetrieveAccountResponseFeatures
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveAccountResponseFeatures) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

var (
	retrieveAccountResponsePricingTierFieldID                      = big.NewInt(1 << 0)
	retrieveAccountResponsePricingTierFieldName                    = big.NewInt(1 << 1)
	retrieveAccountResponsePricingTierFieldDescription             = big.NewInt(1 << 2)
	retrieveAccountResponsePricingTierFieldCurrency                = big.NewInt(1 << 3)
	retrieveAccountResponsePricingTierFieldRatePerMinute           = big.NewInt(1 << 4)
	retrieveAccountResponsePricingTierFieldBillingIncrementSeconds = big.NewInt(1 << 5)
	retrieveAccountResponsePricingTierFieldMinimumDurationSeconds  = big.NewInt(1 << 6)
	retrieveAccountResponsePricingTierFieldIsActive                = big.NewInt(1 << 7)
	retrieveAccountResponsePricingTierFieldIsDefault               = big.NewInt(1 << 8)
)

type RetrieveAccountResponsePricingTier struct {
	ID                      string  `json:"id" url:"id"`
	Name                    string  `json:"name" url:"name"`
	Description             string  `json:"description" url:"description"`
	Currency                string  `json:"currency" url:"currency"`
	RatePerMinute           float64 `json:"rate_per_minute" url:"rate_per_minute"`
	BillingIncrementSeconds int     `json:"billing_increment_seconds" url:"billing_increment_seconds"`
	MinimumDurationSeconds  int     `json:"minimum_duration_seconds" url:"minimum_duration_seconds"`
	IsActive                bool    `json:"is_active" url:"is_active"`
	IsDefault               bool    `json:"is_default" url:"is_default"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveAccountResponsePricingTier) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RetrieveAccountResponsePricingTier) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RetrieveAccountResponsePricingTier) GetDescription() string {
	if r == nil {
		return ""
	}
	return r.Description
}

func (r *RetrieveAccountResponsePricingTier) GetCurrency() string {
	if r == nil {
		return ""
	}
	return r.Currency
}

func (r *RetrieveAccountResponsePricingTier) GetRatePerMinute() float64 {
	if r == nil {
		return 0
	}
	return r.RatePerMinute
}

func (r *RetrieveAccountResponsePricingTier) GetBillingIncrementSeconds() int {
	if r == nil {
		return 0
	}
	return r.BillingIncrementSeconds
}

func (r *RetrieveAccountResponsePricingTier) GetMinimumDurationSeconds() int {
	if r == nil {
		return 0
	}
	return r.MinimumDurationSeconds
}

func (r *RetrieveAccountResponsePricingTier) GetIsActive() bool {
	if r == nil {
		return false
	}
	return r.IsActive
}

func (r *RetrieveAccountResponsePricingTier) GetIsDefault() bool {
	if r == nil {
		return false
	}
	return r.IsDefault
}

func (r *RetrieveAccountResponsePricingTier) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RetrieveAccountResponsePricingTier) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetID(id string) {
	r.ID = id
	r.require(retrieveAccountResponsePricingTierFieldID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetName(name string) {
	r.Name = name
	r.require(retrieveAccountResponsePricingTierFieldName)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetDescription(description string) {
	r.Description = description
	r.require(retrieveAccountResponsePricingTierFieldDescription)
}

// SetCurrency sets the Currency field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetCurrency(currency string) {
	r.Currency = currency
	r.require(retrieveAccountResponsePricingTierFieldCurrency)
}

// SetRatePerMinute sets the RatePerMinute field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetRatePerMinute(ratePerMinute float64) {
	r.RatePerMinute = ratePerMinute
	r.require(retrieveAccountResponsePricingTierFieldRatePerMinute)
}

// SetBillingIncrementSeconds sets the BillingIncrementSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetBillingIncrementSeconds(billingIncrementSeconds int) {
	r.BillingIncrementSeconds = billingIncrementSeconds
	r.require(retrieveAccountResponsePricingTierFieldBillingIncrementSeconds)
}

// SetMinimumDurationSeconds sets the MinimumDurationSeconds field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetMinimumDurationSeconds(minimumDurationSeconds int) {
	r.MinimumDurationSeconds = minimumDurationSeconds
	r.require(retrieveAccountResponsePricingTierFieldMinimumDurationSeconds)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetIsActive(isActive bool) {
	r.IsActive = isActive
	r.require(retrieveAccountResponsePricingTierFieldIsActive)
}

// SetIsDefault sets the IsDefault field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveAccountResponsePricingTier) SetIsDefault(isDefault bool) {
	r.IsDefault = isDefault
	r.require(retrieveAccountResponsePricingTierFieldIsDefault)
}

func (r *RetrieveAccountResponsePricingTier) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveAccountResponsePricingTier
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveAccountResponsePricingTier(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveAccountResponsePricingTier) MarshalJSON() ([]byte, error) {
	type embed RetrieveAccountResponsePricingTier
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveAccountResponsePricingTier) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
