// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	big "math/big"
)

var (
	muteMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	muteMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	muteMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type MuteMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	// Member ID, comma-separated IDs, or `all`
	MemberID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MuteMemberRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MuteMemberRequest) SetAuthID(authID string) {
	m.AuthID = authID
	m.require(muteMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MuteMemberRequest) SetConferenceName(conferenceName string) {
	m.ConferenceName = conferenceName
	m.require(muteMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MuteMemberRequest) SetMemberID(memberID string) {
	m.MemberID = memberID
	m.require(muteMemberRequestFieldMemberID)
}

var (
	unmuteMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	unmuteMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	unmuteMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type UnmuteMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UnmuteMemberRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnmuteMemberRequest) SetAuthID(authID string) {
	u.AuthID = authID
	u.require(unmuteMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnmuteMemberRequest) SetConferenceName(conferenceName string) {
	u.ConferenceName = conferenceName
	u.require(unmuteMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UnmuteMemberRequest) SetMemberID(memberID string) {
	u.MemberID = memberID
	u.require(unmuteMemberRequestFieldMemberID)
}
