// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	big "math/big"
)

var (
	deafMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	deafMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	deafMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type DeafMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeafMemberRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeafMemberRequest) SetAuthID(authID string) {
	d.AuthID = authID
	d.require(deafMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeafMemberRequest) SetConferenceName(conferenceName string) {
	d.ConferenceName = conferenceName
	d.require(deafMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeafMemberRequest) SetMemberID(memberID string) {
	d.MemberID = memberID
	d.require(deafMemberRequestFieldMemberID)
}

var (
	hangupMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	hangupMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	hangupMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type HangupMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (h *HangupMemberRequest) require(field *big.Int) {
	if h.explicitFields == nil {
		h.explicitFields = big.NewInt(0)
	}
	h.explicitFields.Or(h.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HangupMemberRequest) SetAuthID(authID string) {
	h.AuthID = authID
	h.require(hangupMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HangupMemberRequest) SetConferenceName(conferenceName string) {
	h.ConferenceName = conferenceName
	h.require(hangupMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (h *HangupMemberRequest) SetMemberID(memberID string) {
	h.MemberID = memberID
	h.require(hangupMemberRequestFieldMemberID)
}

var (
	kickMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	kickMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	kickMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type KickMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (k *KickMemberRequest) require(field *big.Int) {
	if k.explicitFields == nil {
		k.explicitFields = big.NewInt(0)
	}
	k.explicitFields.Or(k.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KickMemberRequest) SetAuthID(authID string) {
	k.AuthID = authID
	k.require(kickMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KickMemberRequest) SetConferenceName(conferenceName string) {
	k.ConferenceName = conferenceName
	k.require(kickMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (k *KickMemberRequest) SetMemberID(memberID string) {
	k.MemberID = memberID
	k.require(kickMemberRequestFieldMemberID)
}

var (
	playAudioMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	playAudioMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	playAudioMemberRequestFieldMemberID       = big.NewInt(1 << 2)
	playAudioMemberRequestFieldURL            = big.NewInt(1 << 3)
)

type PlayAudioMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`
	// URL of the audio file to play
	URL string `json:"url" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PlayAudioMemberRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlayAudioMemberRequest) SetAuthID(authID string) {
	p.AuthID = authID
	p.require(playAudioMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlayAudioMemberRequest) SetConferenceName(conferenceName string) {
	p.ConferenceName = conferenceName
	p.require(playAudioMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlayAudioMemberRequest) SetMemberID(memberID string) {
	p.MemberID = memberID
	p.require(playAudioMemberRequestFieldMemberID)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PlayAudioMemberRequest) SetURL(url string) {
	p.URL = url
	p.require(playAudioMemberRequestFieldURL)
}

func (p *PlayAudioMemberRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PlayAudioMemberRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PlayAudioMemberRequest(body)
	return nil
}

func (p *PlayAudioMemberRequest) MarshalJSON() ([]byte, error) {
	type embed PlayAudioMemberRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	stopAudioMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	stopAudioMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	stopAudioMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type StopAudioMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *StopAudioMemberRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAudioMemberRequest) SetAuthID(authID string) {
	s.AuthID = authID
	s.require(stopAudioMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAudioMemberRequest) SetConferenceName(conferenceName string) {
	s.ConferenceName = conferenceName
	s.require(stopAudioMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *StopAudioMemberRequest) SetMemberID(memberID string) {
	s.MemberID = memberID
	s.require(stopAudioMemberRequestFieldMemberID)
}

var (
	undeafMemberRequestFieldAuthID         = big.NewInt(1 << 0)
	undeafMemberRequestFieldConferenceName = big.NewInt(1 << 1)
	undeafMemberRequestFieldMemberID       = big.NewInt(1 << 2)
)

type UndeafMemberRequest struct {
	// Your account Auth ID
	AuthID         string `json:"-" url:"-"`
	ConferenceName string `json:"-" url:"-"`
	MemberID       string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UndeafMemberRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UndeafMemberRequest) SetAuthID(authID string) {
	u.AuthID = authID
	u.require(undeafMemberRequestFieldAuthID)
}

// SetConferenceName sets the ConferenceName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UndeafMemberRequest) SetConferenceName(conferenceName string) {
	u.ConferenceName = conferenceName
	u.require(undeafMemberRequestFieldConferenceName)
}

// SetMemberID sets the MemberID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UndeafMemberRequest) SetMemberID(memberID string) {
	u.MemberID = memberID
	u.require(undeafMemberRequestFieldMemberID)
}
