// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersSendDtmfRequest(t *testing.T) {
	t.Run("SetAuthID", func(t *testing.T) {
		obj := &SendDtmfRequest{}
		var fernTestValueAuthID string
		obj.SetAuthID(fernTestValueAuthID)
		assert.Equal(t, fernTestValueAuthID, obj.AuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCallUUID", func(t *testing.T) {
		obj := &SendDtmfRequest{}
		var fernTestValueCallUUID string
		obj.SetCallUUID(fernTestValueCallUUID)
		assert.Equal(t, fernTestValueCallUUID, obj.CallUUID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetDigits", func(t *testing.T) {
		obj := &SendDtmfRequest{}
		var fernTestValueDigits string
		obj.SetDigits(fernTestValueDigits)
		assert.Equal(t, fernTestValueDigits, obj.Digits)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLeg", func(t *testing.T) {
		obj := &SendDtmfRequest{}
		var fernTestValueLeg *SendDtmfRequestLeg
		obj.SetLeg(fernTestValueLeg)
		assert.Equal(t, fernTestValueLeg, obj.Leg)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSendDtmfRequest(t *testing.T) {
	t.Run("SetAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SendDtmfRequest{}
		var fernTestValueAuthID string

		// Act
		obj.SetAuthID(fernTestValueAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCallUUID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SendDtmfRequest{}
		var fernTestValueCallUUID string

		// Act
		obj.SetCallUUID(fernTestValueCallUUID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetDigits_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SendDtmfRequest{}
		var fernTestValueDigits string

		// Act
		obj.SetDigits(fernTestValueDigits)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLeg_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SendDtmfRequest{}
		var fernTestValueLeg *SendDtmfRequestLeg

		// Act
		obj.SetLeg(fernTestValueLeg)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestEnumSendDtmfRequestLeg(t *testing.T) {
	t.Run("NewFromString_aleg", func(t *testing.T) {
		t.Parallel()
		val, err := NewSendDtmfRequestLegFromString("aleg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SendDtmfRequestLeg("aleg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_bleg", func(t *testing.T) {
		t.Parallel()
		val, err := NewSendDtmfRequestLegFromString("bleg")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SendDtmfRequestLeg("bleg"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_both", func(t *testing.T) {
		t.Parallel()
		val, err := NewSendDtmfRequestLegFromString("both")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SendDtmfRequestLeg("both"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSendDtmfRequestLegFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSendDtmfRequestLegFromString("aleg")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}
