// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	assert "github.com/stretchr/testify/assert"
	require "github.com/stretchr/testify/require"
	testing "testing"
)

func TestSettersConfirmSubaccountCinRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCompanyName", func(t *testing.T) {
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueCompanyName string
		obj.SetCompanyName(fernTestValueCompanyName)
		assert.Equal(t, fernTestValueCompanyName, obj.CompanyName)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetSelectedCin", func(t *testing.T) {
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueSelectedCin string
		obj.SetSelectedCin(fernTestValueSelectedCin)
		assert.Equal(t, fernTestValueSelectedCin, obj.SelectedCin)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitConfirmSubaccountCinRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCompanyName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueCompanyName string

		// Act
		obj.SetCompanyName(fernTestValueCompanyName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetSelectedCin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &ConfirmSubaccountCinRequest{}
		var fernTestValueSelectedCin string

		// Act
		obj.SetSelectedCin(fernTestValueSelectedCin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersCreateSubaccountKycSessionRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccountAuthID", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueAccountAuthID string
		obj.SetAccountAuthID(fernTestValueAccountAuthID)
		assert.Equal(t, fernTestValueAccountAuthID, obj.AccountAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetFlowType", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueFlowType CreateSubaccountKycSessionRequestFlowType
		obj.SetFlowType(fernTestValueFlowType)
		assert.Equal(t, fernTestValueFlowType, obj.FlowType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCustomerEmail", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueCustomerEmail *string
		obj.SetCustomerEmail(fernTestValueCustomerEmail)
		assert.Equal(t, fernTestValueCustomerEmail, obj.CustomerEmail)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRedirectURL", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueRedirectURL *string
		obj.SetRedirectURL(fernTestValueRedirectURL)
		assert.Equal(t, fernTestValueRedirectURL, obj.RedirectURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetWebhookURL", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueWebhookURL *string
		obj.SetWebhookURL(fernTestValueWebhookURL)
		assert.Equal(t, fernTestValueWebhookURL, obj.WebhookURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetExpiresInDays", func(t *testing.T) {
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueExpiresInDays *int
		obj.SetExpiresInDays(fernTestValueExpiresInDays)
		assert.Equal(t, fernTestValueExpiresInDays, obj.ExpiresInDays)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitCreateSubaccountKycSessionRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccountAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueAccountAuthID string

		// Act
		obj.SetAccountAuthID(fernTestValueAccountAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetFlowType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueFlowType CreateSubaccountKycSessionRequestFlowType

		// Act
		obj.SetFlowType(fernTestValueFlowType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCustomerEmail_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueCustomerEmail *string

		// Act
		obj.SetCustomerEmail(fernTestValueCustomerEmail)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRedirectURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueRedirectURL *string

		// Act
		obj.SetRedirectURL(fernTestValueRedirectURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetWebhookURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueWebhookURL *string

		// Act
		obj.SetWebhookURL(fernTestValueWebhookURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetExpiresInDays_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &CreateSubaccountKycSessionRequest{}
		var fernTestValueExpiresInDays *int

		// Act
		obj.SetExpiresInDays(fernTestValueExpiresInDays)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersGetSubaccountKycStatusRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &GetSubaccountKycStatusRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitGetSubaccountKycStatusRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &GetSubaccountKycStatusRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSearchSubaccountCinRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &SearchSubaccountCinRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetCompanyName", func(t *testing.T) {
		obj := &SearchSubaccountCinRequest{}
		var fernTestValueCompanyName string
		obj.SetCompanyName(fernTestValueCompanyName)
		assert.Equal(t, fernTestValueCompanyName, obj.CompanyName)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSearchSubaccountCinRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchSubaccountCinRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetCompanyName_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SearchSubaccountCinRequest{}
		var fernTestValueCompanyName string

		// Act
		obj.SetCompanyName(fernTestValueCompanyName)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSubaccountDigilockerInitiateRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetRedirectURL", func(t *testing.T) {
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueRedirectURL string
		obj.SetRedirectURL(fernTestValueRedirectURL)
		assert.Equal(t, fernTestValueRedirectURL, obj.RedirectURL)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOauthState", func(t *testing.T) {
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueOauthState *string
		obj.SetOauthState(fernTestValueOauthState)
		assert.Equal(t, fernTestValueOauthState, obj.OauthState)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSubaccountDigilockerInitiateRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetRedirectURL_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueRedirectURL string

		// Act
		obj.SetRedirectURL(fernTestValueRedirectURL)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOauthState_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerInitiateRequest{}
		var fernTestValueOauthState *string

		// Act
		obj.SetOauthState(fernTestValueOauthState)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSubaccountDigilockerVerifyRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetAccessRequestID", func(t *testing.T) {
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueAccessRequestID string
		obj.SetAccessRequestID(fernTestValueAccessRequestID)
		assert.Equal(t, fernTestValueAccessRequestID, obj.AccessRequestID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetLinkedNumber", func(t *testing.T) {
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueLinkedNumber *string
		obj.SetLinkedNumber(fernTestValueLinkedNumber)
		assert.Equal(t, fernTestValueLinkedNumber, obj.LinkedNumber)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitSubaccountDigilockerVerifyRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetAccessRequestID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueAccessRequestID string

		// Act
		obj.SetAccessRequestID(fernTestValueAccessRequestID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetLinkedNumber_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubaccountDigilockerVerifyRequest{}
		var fernTestValueLinkedNumber *string

		// Act
		obj.SetLinkedNumber(fernTestValueLinkedNumber)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersSubAccountKycStatus(t *testing.T) {
	t.Run("SetSubAccountID", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueSubAccountID *string
		obj.SetSubAccountID(fernTestValueSubAccountID)
		assert.Equal(t, fernTestValueSubAccountID, obj.SubAccountID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKycMode", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueKycMode *SubAccountKycStatusKycMode
		obj.SetKycMode(fernTestValueKycMode)
		assert.Equal(t, fernTestValueKycMode, obj.KycMode)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetBusinessType", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueBusinessType *string
		obj.SetBusinessType(fernTestValueBusinessType)
		assert.Equal(t, fernTestValueBusinessType, obj.BusinessType)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetOverallStatus", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueOverallStatus *SubAccountKycStatusOverallStatus
		obj.SetOverallStatus(fernTestValueOverallStatus)
		assert.Equal(t, fernTestValueOverallStatus, obj.OverallStatus)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetKycCallsBlocked", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueKycCallsBlocked *bool
		obj.SetKycCallsBlocked(fernTestValueKycCallsBlocked)
		assert.Equal(t, fernTestValueKycCallsBlocked, obj.KycCallsBlocked)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetVerifications", func(t *testing.T) {
		obj := &SubAccountKycStatus{}
		var fernTestValueVerifications map[string]SubAccountKycStatusVerificationsValue
		obj.SetVerifications(fernTestValueVerifications)
		assert.Equal(t, fernTestValueVerifications, obj.Verifications)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestGettersSubAccountKycStatus(t *testing.T) {
	t.Run("GetSubAccountID", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected *string
		obj.SubAccountID = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetSubAccountID(), "getter should return the property value")
	})

	t.Run("GetSubAccountID_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.SubAccountID = nil

		// Act & Assert
		assert.Nil(t, obj.GetSubAccountID(), "getter should return nil when property is nil")
	})

	t.Run("GetSubAccountID_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetSubAccountID() // Should return zero value
	})

	t.Run("GetKycMode", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected *SubAccountKycStatusKycMode
		obj.KycMode = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKycMode(), "getter should return the property value")
	})

	t.Run("GetKycMode_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.KycMode = nil

		// Act & Assert
		assert.Nil(t, obj.GetKycMode(), "getter should return nil when property is nil")
	})

	t.Run("GetKycMode_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKycMode() // Should return zero value
	})

	t.Run("GetBusinessType", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected *string
		obj.BusinessType = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetBusinessType(), "getter should return the property value")
	})

	t.Run("GetBusinessType_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.BusinessType = nil

		// Act & Assert
		assert.Nil(t, obj.GetBusinessType(), "getter should return nil when property is nil")
	})

	t.Run("GetBusinessType_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetBusinessType() // Should return zero value
	})

	t.Run("GetOverallStatus", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected *SubAccountKycStatusOverallStatus
		obj.OverallStatus = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetOverallStatus(), "getter should return the property value")
	})

	t.Run("GetOverallStatus_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.OverallStatus = nil

		// Act & Assert
		assert.Nil(t, obj.GetOverallStatus(), "getter should return nil when property is nil")
	})

	t.Run("GetOverallStatus_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetOverallStatus() // Should return zero value
	})

	t.Run("GetKycCallsBlocked", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected *bool
		obj.KycCallsBlocked = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetKycCallsBlocked(), "getter should return the property value")
	})

	t.Run("GetKycCallsBlocked_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.KycCallsBlocked = nil

		// Act & Assert
		assert.Nil(t, obj.GetKycCallsBlocked(), "getter should return nil when property is nil")
	})

	t.Run("GetKycCallsBlocked_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetKycCallsBlocked() // Should return zero value
	})

	t.Run("GetVerifications", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var expected map[string]SubAccountKycStatusVerificationsValue
		obj.Verifications = expected

		// Act & Assert
		assert.Equal(t, expected, obj.GetVerifications(), "getter should return the property value")
	})

	t.Run("GetVerifications_NilValue", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		obj.Verifications = nil

		// Act & Assert
		assert.Nil(t, obj.GetVerifications(), "getter should return nil when property is nil")
	})

	t.Run("GetVerifications_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		// Should not panic - getters should handle nil receiver gracefully
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("Getter panicked on nil receiver: %v", r)
			}
		}()
		_ = obj.GetVerifications() // Should return zero value
	})

}

func TestSettersMarkExplicitSubAccountKycStatus(t *testing.T) {
	t.Run("SetSubAccountID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueSubAccountID *string

		// Act
		obj.SetSubAccountID(fernTestValueSubAccountID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKycMode_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueKycMode *SubAccountKycStatusKycMode

		// Act
		obj.SetKycMode(fernTestValueKycMode)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetBusinessType_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueBusinessType *string

		// Act
		obj.SetBusinessType(fernTestValueBusinessType)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetOverallStatus_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueOverallStatus *SubAccountKycStatusOverallStatus

		// Act
		obj.SetOverallStatus(fernTestValueOverallStatus)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetKycCallsBlocked_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueKycCallsBlocked *bool

		// Act
		obj.SetKycCallsBlocked(fernTestValueKycCallsBlocked)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetVerifications_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}
		var fernTestValueVerifications map[string]SubAccountKycStatusVerificationsValue

		// Act
		obj.SetVerifications(fernTestValueVerifications)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVerifySubaccountGstRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &VerifySubaccountGstRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetGstin", func(t *testing.T) {
		obj := &VerifySubaccountGstRequest{}
		var fernTestValueGstin string
		obj.SetGstin(fernTestValueGstin)
		assert.Equal(t, fernTestValueGstin, obj.Gstin)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitVerifySubaccountGstRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifySubaccountGstRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetGstin_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifySubaccountGstRequest{}
		var fernTestValueGstin string

		// Act
		obj.SetGstin(fernTestValueGstin)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestSettersVerifySubaccountPanRequest(t *testing.T) {
	t.Run("SetSubAuthID", func(t *testing.T) {
		obj := &VerifySubaccountPanRequest{}
		var fernTestValueSubAuthID string
		obj.SetSubAuthID(fernTestValueSubAuthID)
		assert.Equal(t, fernTestValueSubAuthID, obj.SubAuthID)
		assert.NotNil(t, obj.explicitFields)
	})

	t.Run("SetPan", func(t *testing.T) {
		obj := &VerifySubaccountPanRequest{}
		var fernTestValuePan string
		obj.SetPan(fernTestValuePan)
		assert.Equal(t, fernTestValuePan, obj.Pan)
		assert.NotNil(t, obj.explicitFields)
	})

}

func TestSettersMarkExplicitVerifySubaccountPanRequest(t *testing.T) {
	t.Run("SetSubAuthID_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifySubaccountPanRequest{}
		var fernTestValueSubAuthID string

		// Act
		obj.SetSubAuthID(fernTestValueSubAuthID)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

	t.Run("SetPan_MarksExplicit", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &VerifySubaccountPanRequest{}
		var fernTestValuePan string

		// Act
		obj.SetPan(fernTestValuePan)

		// Assert - object with explicitly set field can be marshaled/unmarshaled
		bytes, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed for test setup")

		// This test ensures JSON marshaling and unmarshaling succeed when the field has a zero/nil value
		// Detect if marshaled JSON is an object or primitive to use correct unmarshal target
		if len(bytes) > 0 && bytes[0] == '{' {
			// JSON object - unmarshal into map
			var unmarshaled map[string]interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		} else {
			// JSON primitive (string, number, boolean, null) - unmarshal into interface{}
			var unmarshaled interface{}
			err = json.Unmarshal(bytes, &unmarshaled)
			require.NoError(t, err, "unmarshaling should succeed for test verification")
		}

		// Note: This does not explicitly assert the presence of a specific JSON field
		// It verifies that setting a field via setter allows successful JSON round-trip
	})

}

func TestJSONMarshalingSubAccountKycStatus(t *testing.T) {
	t.Run("MarshalUnmarshal", func(t *testing.T) {
		t.Parallel()
		// Arrange
		obj := &SubAccountKycStatus{}

		// Act - Marshal to JSON
		data, err := json.Marshal(obj)
		require.NoError(t, err, "marshaling should succeed")
		assert.NotNil(t, data, "marshaled data should not be nil")
		assert.NotEmpty(t, data, "marshaled data should not be empty")

		// Unmarshal back and verify round-trip
		var unmarshaled SubAccountKycStatus
		err = json.Unmarshal(data, &unmarshaled)
		assert.NoError(t, err, "round-trip unmarshal should succeed")
	})

	t.Run("UnmarshalInvalidJSON", func(t *testing.T) {
		t.Parallel()
		var obj SubAccountKycStatus
		err := json.Unmarshal([]byte(`{invalid json}`), &obj)
		assert.Error(t, err, "unmarshaling invalid JSON should return an error")
	})

	t.Run("UnmarshalEmptyObject", func(t *testing.T) {
		t.Parallel()
		var obj SubAccountKycStatus
		err := json.Unmarshal([]byte(`{}`), &obj)
		assert.NoError(t, err, "unmarshaling empty object should succeed")
	})
}

func TestStringSubAccountKycStatus(t *testing.T) {
	t.Run("StringMethod", func(t *testing.T) {
		t.Parallel()
		obj := &SubAccountKycStatus{}
		result := obj.String()
		assert.NotEmpty(t, result, "String() should return a non-empty representation")
	})

	t.Run("StringMethod_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		result := obj.String()
		assert.Equal(t, "<nil>", result, "String() should return <nil> for nil receiver")
	})
}

func TestEnumCreateSubaccountKycSessionRequestFlowType(t *testing.T) {
	t.Run("NewFromString_email", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateSubaccountKycSessionRequestFlowTypeFromString("email")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateSubaccountKycSessionRequestFlowType("email"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_redirect", func(t *testing.T) {
		t.Parallel()
		val, err := NewCreateSubaccountKycSessionRequestFlowTypeFromString("redirect")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, CreateSubaccountKycSessionRequestFlowType("redirect"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewCreateSubaccountKycSessionRequestFlowTypeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewCreateSubaccountKycSessionRequestFlowTypeFromString("email")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumSubAccountKycStatusKycMode(t *testing.T) {
	t.Run("NewFromString_personal_use", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusKycModeFromString("personal_use")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusKycMode("personal_use"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_customer_use", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusKycModeFromString("customer_use")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusKycMode("customer_use"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSubAccountKycStatusKycModeFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSubAccountKycStatusKycModeFromString("personal_use")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumSubAccountKycStatusOverallStatus(t *testing.T) {
	t.Run("NewFromString_not_started", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusOverallStatusFromString("not_started")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusOverallStatus("not_started"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_pending", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusOverallStatusFromString("pending")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusOverallStatus("pending"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_verified", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusOverallStatusFromString("verified")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusOverallStatus("verified"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusOverallStatusFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusOverallStatus("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSubAccountKycStatusOverallStatusFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSubAccountKycStatusOverallStatusFromString("not_started")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestEnumSubAccountKycStatusVerificationsValue(t *testing.T) {
	t.Run("NewFromString_not_started", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusVerificationsValueFromString("not_started")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusVerificationsValue("not_started"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_pending", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusVerificationsValueFromString("pending")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusVerificationsValue("pending"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_verified", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusVerificationsValueFromString("verified")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusVerificationsValue("verified"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_failed", func(t *testing.T) {
		t.Parallel()
		val, err := NewSubAccountKycStatusVerificationsValueFromString("failed")
		assert.NoError(t, err, "valid enum value should not return error")
		assert.Equal(t, SubAccountKycStatusVerificationsValue("failed"), val, "enum value should match expected wire value")
	})

	t.Run("NewFromString_Invalid", func(t *testing.T) {
		_, err := NewSubAccountKycStatusVerificationsValueFromString("invalid_value_that_does_not_exist")
		assert.Error(t, err)
	})

	t.Run("Ptr", func(t *testing.T) {
		val, err := NewSubAccountKycStatusVerificationsValueFromString("not_started")
		assert.NoError(t, err)
		ptr := val.Ptr()
		assert.NotNil(t, ptr)
		assert.Equal(t, val, *ptr)
	})
}

func TestExtraPropertiesSubAccountKycStatus(t *testing.T) {
	t.Run("GetExtraProperties", func(t *testing.T) {
		t.Parallel()
		obj := &SubAccountKycStatus{}
		// Should not panic when calling GetExtraProperties()
		defer func() {
			if r := recover(); r != nil {
				t.Errorf("GetExtraProperties() panicked: %v", r)
			}
		}()
		extraProps := obj.GetExtraProperties()
		// Result can be nil or an empty/non-empty map
		_ = extraProps
	})

	t.Run("GetExtraProperties_NilReceiver", func(t *testing.T) {
		t.Parallel()
		var obj *SubAccountKycStatus
		extraProps := obj.GetExtraProperties()
		assert.Nil(t, extraProps, "nil receiver should return nil without panicking")
	})
}
