// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	big "math/big"
)

var (
	mockConfirmSubaccountCinRequestFieldSubAuthID   = big.NewInt(1 << 0)
	mockConfirmSubaccountCinRequestFieldCompanyName = big.NewInt(1 << 1)
	mockConfirmSubaccountCinRequestFieldSelectedCin = big.NewInt(1 << 2)
)

type MockConfirmSubaccountCinRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	CompanyName string `json:"company_name" url:"-"`
	SelectedCin string `json:"selected_cin" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockConfirmSubaccountCinRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockConfirmSubaccountCinRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockConfirmSubaccountCinRequestFieldSubAuthID)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockConfirmSubaccountCinRequest) SetCompanyName(companyName string) {
	m.CompanyName = companyName
	m.require(mockConfirmSubaccountCinRequestFieldCompanyName)
}

// SetSelectedCin sets the SelectedCin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockConfirmSubaccountCinRequest) SetSelectedCin(selectedCin string) {
	m.SelectedCin = selectedCin
	m.require(mockConfirmSubaccountCinRequestFieldSelectedCin)
}

func (m *MockConfirmSubaccountCinRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockConfirmSubaccountCinRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockConfirmSubaccountCinRequest(body)
	return nil
}

func (m *MockConfirmSubaccountCinRequest) MarshalJSON() ([]byte, error) {
	type embed MockConfirmSubaccountCinRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockFinalizePendingKycRequestFieldSubAuthID        = big.NewInt(1 << 0)
	mockFinalizePendingKycRequestFieldVerificationType = big.NewInt(1 << 1)
	mockFinalizePendingKycRequestFieldOutcome          = big.NewInt(1 << 2)
)

type MockFinalizePendingKycRequest struct {
	// The sub-account's Auth ID.
	SubAuthID        string                                        `json:"-" url:"-"`
	VerificationType MockFinalizePendingKycRequestVerificationType `json:"verification_type" url:"-"`
	Outcome          MockFinalizePendingKycRequestOutcome          `json:"outcome" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockFinalizePendingKycRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockFinalizePendingKycRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockFinalizePendingKycRequestFieldSubAuthID)
}

// SetVerificationType sets the VerificationType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockFinalizePendingKycRequest) SetVerificationType(verificationType MockFinalizePendingKycRequestVerificationType) {
	m.VerificationType = verificationType
	m.require(mockFinalizePendingKycRequestFieldVerificationType)
}

// SetOutcome sets the Outcome field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockFinalizePendingKycRequest) SetOutcome(outcome MockFinalizePendingKycRequestOutcome) {
	m.Outcome = outcome
	m.require(mockFinalizePendingKycRequestFieldOutcome)
}

func (m *MockFinalizePendingKycRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockFinalizePendingKycRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockFinalizePendingKycRequest(body)
	return nil
}

func (m *MockFinalizePendingKycRequest) MarshalJSON() ([]byte, error) {
	type embed MockFinalizePendingKycRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockSearchSubaccountCinRequestFieldSubAuthID   = big.NewInt(1 << 0)
	mockSearchSubaccountCinRequestFieldCompanyName = big.NewInt(1 << 1)
)

type MockSearchSubaccountCinRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	CompanyName string `json:"company_name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockSearchSubaccountCinRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSearchSubaccountCinRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockSearchSubaccountCinRequestFieldSubAuthID)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSearchSubaccountCinRequest) SetCompanyName(companyName string) {
	m.CompanyName = companyName
	m.require(mockSearchSubaccountCinRequestFieldCompanyName)
}

func (m *MockSearchSubaccountCinRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockSearchSubaccountCinRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockSearchSubaccountCinRequest(body)
	return nil
}

func (m *MockSearchSubaccountCinRequest) MarshalJSON() ([]byte, error) {
	type embed MockSearchSubaccountCinRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockSubaccountDigilockerInitiateRequestFieldSubAuthID   = big.NewInt(1 << 0)
	mockSubaccountDigilockerInitiateRequestFieldRedirectURL = big.NewInt(1 << 1)
)

type MockSubaccountDigilockerInitiateRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	RedirectURL string `json:"redirect_url" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockSubaccountDigilockerInitiateRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSubaccountDigilockerInitiateRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockSubaccountDigilockerInitiateRequestFieldSubAuthID)
}

// SetRedirectURL sets the RedirectURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSubaccountDigilockerInitiateRequest) SetRedirectURL(redirectURL string) {
	m.RedirectURL = redirectURL
	m.require(mockSubaccountDigilockerInitiateRequestFieldRedirectURL)
}

func (m *MockSubaccountDigilockerInitiateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockSubaccountDigilockerInitiateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockSubaccountDigilockerInitiateRequest(body)
	return nil
}

func (m *MockSubaccountDigilockerInitiateRequest) MarshalJSON() ([]byte, error) {
	type embed MockSubaccountDigilockerInitiateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockSubaccountDigilockerVerifyRequestFieldSubAuthID       = big.NewInt(1 << 0)
	mockSubaccountDigilockerVerifyRequestFieldAccessRequestID = big.NewInt(1 << 1)
)

type MockSubaccountDigilockerVerifyRequest struct {
	// The sub-account's Auth ID.
	SubAuthID       string                                               `json:"-" url:"-"`
	AccessRequestID MockSubaccountDigilockerVerifyRequestAccessRequestID `json:"access_request_id" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockSubaccountDigilockerVerifyRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSubaccountDigilockerVerifyRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockSubaccountDigilockerVerifyRequestFieldSubAuthID)
}

// SetAccessRequestID sets the AccessRequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockSubaccountDigilockerVerifyRequest) SetAccessRequestID(accessRequestID MockSubaccountDigilockerVerifyRequestAccessRequestID) {
	m.AccessRequestID = accessRequestID
	m.require(mockSubaccountDigilockerVerifyRequestFieldAccessRequestID)
}

func (m *MockSubaccountDigilockerVerifyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockSubaccountDigilockerVerifyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockSubaccountDigilockerVerifyRequest(body)
	return nil
}

func (m *MockSubaccountDigilockerVerifyRequest) MarshalJSON() ([]byte, error) {
	type embed MockSubaccountDigilockerVerifyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockVerifySubaccountGstRequestFieldSubAuthID = big.NewInt(1 << 0)
	mockVerifySubaccountGstRequestFieldGstin     = big.NewInt(1 << 1)
)

type MockVerifySubaccountGstRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`
	Gstin     string `json:"gstin" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockVerifySubaccountGstRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockVerifySubaccountGstRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockVerifySubaccountGstRequestFieldSubAuthID)
}

// SetGstin sets the Gstin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockVerifySubaccountGstRequest) SetGstin(gstin string) {
	m.Gstin = gstin
	m.require(mockVerifySubaccountGstRequestFieldGstin)
}

func (m *MockVerifySubaccountGstRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockVerifySubaccountGstRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockVerifySubaccountGstRequest(body)
	return nil
}

func (m *MockVerifySubaccountGstRequest) MarshalJSON() ([]byte, error) {
	type embed MockVerifySubaccountGstRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	mockVerifySubaccountPanRequestFieldSubAuthID = big.NewInt(1 << 0)
	mockVerifySubaccountPanRequestFieldPan       = big.NewInt(1 << 1)
)

type MockVerifySubaccountPanRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`
	Pan       string `json:"pan" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (m *MockVerifySubaccountPanRequest) require(field *big.Int) {
	if m.explicitFields == nil {
		m.explicitFields = big.NewInt(0)
	}
	m.explicitFields.Or(m.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockVerifySubaccountPanRequest) SetSubAuthID(subAuthID string) {
	m.SubAuthID = subAuthID
	m.require(mockVerifySubaccountPanRequestFieldSubAuthID)
}

// SetPan sets the Pan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (m *MockVerifySubaccountPanRequest) SetPan(pan string) {
	m.Pan = pan
	m.require(mockVerifySubaccountPanRequestFieldPan)
}

func (m *MockVerifySubaccountPanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler MockVerifySubaccountPanRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*m = MockVerifySubaccountPanRequest(body)
	return nil
}

func (m *MockVerifySubaccountPanRequest) MarshalJSON() ([]byte, error) {
	type embed MockVerifySubaccountPanRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*m),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, m.explicitFields)
	return json.Marshal(explicitMarshaler)
}

type MockFinalizePendingKycRequestOutcome string

const (
	MockFinalizePendingKycRequestOutcomeVerified MockFinalizePendingKycRequestOutcome = "verified"
	MockFinalizePendingKycRequestOutcomeFailed   MockFinalizePendingKycRequestOutcome = "failed"
)

func NewMockFinalizePendingKycRequestOutcomeFromString(s string) (MockFinalizePendingKycRequestOutcome, error) {
	switch s {
	case "verified":
		return MockFinalizePendingKycRequestOutcomeVerified, nil
	case "failed":
		return MockFinalizePendingKycRequestOutcomeFailed, nil
	}
	var t MockFinalizePendingKycRequestOutcome
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MockFinalizePendingKycRequestOutcome) Ptr() *MockFinalizePendingKycRequestOutcome {
	return &m
}

type MockFinalizePendingKycRequestVerificationType string

const (
	MockFinalizePendingKycRequestVerificationTypePan     MockFinalizePendingKycRequestVerificationType = "pan"
	MockFinalizePendingKycRequestVerificationTypeAadhaar MockFinalizePendingKycRequestVerificationType = "aadhaar"
	MockFinalizePendingKycRequestVerificationTypeGst     MockFinalizePendingKycRequestVerificationType = "gst"
	MockFinalizePendingKycRequestVerificationTypeCin     MockFinalizePendingKycRequestVerificationType = "cin"
)

func NewMockFinalizePendingKycRequestVerificationTypeFromString(s string) (MockFinalizePendingKycRequestVerificationType, error) {
	switch s {
	case "pan":
		return MockFinalizePendingKycRequestVerificationTypePan, nil
	case "aadhaar":
		return MockFinalizePendingKycRequestVerificationTypeAadhaar, nil
	case "gst":
		return MockFinalizePendingKycRequestVerificationTypeGst, nil
	case "cin":
		return MockFinalizePendingKycRequestVerificationTypeCin, nil
	}
	var t MockFinalizePendingKycRequestVerificationType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MockFinalizePendingKycRequestVerificationType) Ptr() *MockFinalizePendingKycRequestVerificationType {
	return &m
}

type MockSubaccountDigilockerVerifyRequestAccessRequestID string

const (
	MockSubaccountDigilockerVerifyRequestAccessRequestIDMockArSuccess MockSubaccountDigilockerVerifyRequestAccessRequestID = "MOCK_AR_SUCCESS"
	MockSubaccountDigilockerVerifyRequestAccessRequestIDMockArFail    MockSubaccountDigilockerVerifyRequestAccessRequestID = "MOCK_AR_FAIL"
)

func NewMockSubaccountDigilockerVerifyRequestAccessRequestIDFromString(s string) (MockSubaccountDigilockerVerifyRequestAccessRequestID, error) {
	switch s {
	case "MOCK_AR_SUCCESS":
		return MockSubaccountDigilockerVerifyRequestAccessRequestIDMockArSuccess, nil
	case "MOCK_AR_FAIL":
		return MockSubaccountDigilockerVerifyRequestAccessRequestIDMockArFail, nil
	}
	var t MockSubaccountDigilockerVerifyRequestAccessRequestID
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (m MockSubaccountDigilockerVerifyRequestAccessRequestID) Ptr() *MockSubaccountDigilockerVerifyRequestAccessRequestID {
	return &m
}
