// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	big "math/big"
)

var (
	createSubaccountRequestFieldAuthID       = big.NewInt(1 << 0)
	createSubaccountRequestFieldName         = big.NewInt(1 << 1)
	createSubaccountRequestFieldEmail        = big.NewInt(1 << 2)
	createSubaccountRequestFieldPassword     = big.NewInt(1 << 3)
	createSubaccountRequestFieldKycMode      = big.NewInt(1 << 4)
	createSubaccountRequestFieldBusinessType = big.NewInt(1 << 5)
	createSubaccountRequestFieldEnabled      = big.NewInt(1 << 6)
)

type CreateSubaccountRequest struct {
	// Your account Auth ID
	AuthID string `json:"-" url:"-"`
	// Human-readable name for the sub-account.
	Name string `json:"name" url:"-"`
	// Required when `kyc_mode` is `customer_use`.
	Email *string `json:"email,omitempty" url:"-"`
	// Login password for the sub-account.
	Password *string `json:"password,omitempty" url:"-"`
	// `personal_use` inherits parent KYC. `customer_use` requires
	// the sub-account to complete its own KYC and requires `email`.
	KycMode *CreateSubaccountRequestKycMode `json:"kyc_mode,omitempty" url:"-"`
	// Legal constitution of the customer. Drives which KYC documents are required.
	BusinessType *CreateSubaccountRequestBusinessType `json:"business_type,omitempty" url:"-"`
	Enabled      *bool                                `json:"enabled,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSubaccountRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetAuthID(authID string) {
	c.AuthID = authID
	c.require(createSubaccountRequestFieldAuthID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetName(name string) {
	c.Name = name
	c.require(createSubaccountRequestFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetEmail(email *string) {
	c.Email = email
	c.require(createSubaccountRequestFieldEmail)
}

// SetPassword sets the Password field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetPassword(password *string) {
	c.Password = password
	c.require(createSubaccountRequestFieldPassword)
}

// SetKycMode sets the KycMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetKycMode(kycMode *CreateSubaccountRequestKycMode) {
	c.KycMode = kycMode
	c.require(createSubaccountRequestFieldKycMode)
}

// SetBusinessType sets the BusinessType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetBusinessType(businessType *CreateSubaccountRequestBusinessType) {
	c.BusinessType = businessType
	c.require(createSubaccountRequestFieldBusinessType)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountRequest) SetEnabled(enabled *bool) {
	c.Enabled = enabled
	c.require(createSubaccountRequestFieldEnabled)
}

func (c *CreateSubaccountRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSubaccountRequest(body)
	return nil
}

func (c *CreateSubaccountRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	deleteSubaccountRequestFieldAuthID    = big.NewInt(1 << 0)
	deleteSubaccountRequestFieldSubAuthID = big.NewInt(1 << 1)
)

type DeleteSubaccountRequest struct {
	// Your account Auth ID
	AuthID    string `json:"-" url:"-"`
	SubAuthID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (d *DeleteSubaccountRequest) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSubaccountRequest) SetAuthID(authID string) {
	d.AuthID = authID
	d.require(deleteSubaccountRequestFieldAuthID)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSubaccountRequest) SetSubAuthID(subAuthID string) {
	d.SubAuthID = subAuthID
	d.require(deleteSubaccountRequestFieldSubAuthID)
}

var (
	listSubaccountsRequestFieldAuthID = big.NewInt(1 << 0)
)

type ListSubaccountsRequest struct {
	// Your account Auth ID
	AuthID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (l *ListSubaccountsRequest) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsRequest) SetAuthID(authID string) {
	l.AuthID = authID
	l.require(listSubaccountsRequestFieldAuthID)
}

var (
	retrieveSubaccountRequestFieldAuthID    = big.NewInt(1 << 0)
	retrieveSubaccountRequestFieldSubAuthID = big.NewInt(1 << 1)
)

type RetrieveSubaccountRequest struct {
	// Your account Auth ID
	AuthID    string `json:"-" url:"-"`
	SubAuthID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RetrieveSubaccountRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountRequest) SetAuthID(authID string) {
	r.AuthID = authID
	r.require(retrieveSubaccountRequestFieldAuthID)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountRequest) SetSubAuthID(subAuthID string) {
	r.SubAuthID = subAuthID
	r.require(retrieveSubaccountRequestFieldSubAuthID)
}

// Legal constitution of the customer. Drives which KYC documents are required.
type CreateSubaccountRequestBusinessType string

const (
	CreateSubaccountRequestBusinessTypeIndividual     CreateSubaccountRequestBusinessType = "individual"
	CreateSubaccountRequestBusinessTypeProprietorship CreateSubaccountRequestBusinessType = "proprietorship"
	CreateSubaccountRequestBusinessTypePrivateLimited CreateSubaccountRequestBusinessType = "private_limited"
	CreateSubaccountRequestBusinessTypeLlp            CreateSubaccountRequestBusinessType = "llp"
	CreateSubaccountRequestBusinessTypePartnership    CreateSubaccountRequestBusinessType = "partnership"
	CreateSubaccountRequestBusinessTypePublicLimited  CreateSubaccountRequestBusinessType = "public_limited"
	CreateSubaccountRequestBusinessTypeTrust          CreateSubaccountRequestBusinessType = "trust"
	CreateSubaccountRequestBusinessTypeSociety        CreateSubaccountRequestBusinessType = "society"
	CreateSubaccountRequestBusinessTypeHuf            CreateSubaccountRequestBusinessType = "huf"
	CreateSubaccountRequestBusinessTypeGovernment     CreateSubaccountRequestBusinessType = "government"
)

func NewCreateSubaccountRequestBusinessTypeFromString(s string) (CreateSubaccountRequestBusinessType, error) {
	switch s {
	case "individual":
		return CreateSubaccountRequestBusinessTypeIndividual, nil
	case "proprietorship":
		return CreateSubaccountRequestBusinessTypeProprietorship, nil
	case "private_limited":
		return CreateSubaccountRequestBusinessTypePrivateLimited, nil
	case "llp":
		return CreateSubaccountRequestBusinessTypeLlp, nil
	case "partnership":
		return CreateSubaccountRequestBusinessTypePartnership, nil
	case "public_limited":
		return CreateSubaccountRequestBusinessTypePublicLimited, nil
	case "trust":
		return CreateSubaccountRequestBusinessTypeTrust, nil
	case "society":
		return CreateSubaccountRequestBusinessTypeSociety, nil
	case "huf":
		return CreateSubaccountRequestBusinessTypeHuf, nil
	case "government":
		return CreateSubaccountRequestBusinessTypeGovernment, nil
	}
	var t CreateSubaccountRequestBusinessType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSubaccountRequestBusinessType) Ptr() *CreateSubaccountRequestBusinessType {
	return &c
}

// `personal_use` inherits parent KYC. `customer_use` requires
// the sub-account to complete its own KYC and requires `email`.
type CreateSubaccountRequestKycMode string

const (
	CreateSubaccountRequestKycModePersonalUse CreateSubaccountRequestKycMode = "personal_use"
	CreateSubaccountRequestKycModeCustomerUse CreateSubaccountRequestKycMode = "customer_use"
)

func NewCreateSubaccountRequestKycModeFromString(s string) (CreateSubaccountRequestKycMode, error) {
	switch s {
	case "personal_use":
		return CreateSubaccountRequestKycModePersonalUse, nil
	case "customer_use":
		return CreateSubaccountRequestKycModeCustomerUse, nil
	}
	var t CreateSubaccountRequestKycMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSubaccountRequestKycMode) Ptr() *CreateSubaccountRequestKycMode {
	return &c
}

var (
	createSubaccountResponseFieldMessage         = big.NewInt(1 << 0)
	createSubaccountResponseFieldSubAccount      = big.NewInt(1 << 1)
	createSubaccountResponseFieldAuthCredentials = big.NewInt(1 << 2)
	createSubaccountResponseFieldTokens          = big.NewInt(1 << 3)
)

type CreateSubaccountResponse struct {
	Message         string                                   `json:"message" url:"message"`
	SubAccount      *CreateSubaccountResponseSubAccount      `json:"sub_account" url:"sub_account"`
	AuthCredentials *CreateSubaccountResponseAuthCredentials `json:"auth_credentials" url:"auth_credentials"`
	Tokens          *CreateSubaccountResponseTokens          `json:"tokens" url:"tokens"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSubaccountResponse) GetMessage() string {
	if c == nil {
		return ""
	}
	return c.Message
}

func (c *CreateSubaccountResponse) GetSubAccount() *CreateSubaccountResponseSubAccount {
	if c == nil {
		return nil
	}
	return c.SubAccount
}

func (c *CreateSubaccountResponse) GetAuthCredentials() *CreateSubaccountResponseAuthCredentials {
	if c == nil {
		return nil
	}
	return c.AuthCredentials
}

func (c *CreateSubaccountResponse) GetTokens() *CreateSubaccountResponseTokens {
	if c == nil {
		return nil
	}
	return c.Tokens
}

func (c *CreateSubaccountResponse) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSubaccountResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponse) SetMessage(message string) {
	c.Message = message
	c.require(createSubaccountResponseFieldMessage)
}

// SetSubAccount sets the SubAccount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponse) SetSubAccount(subAccount *CreateSubaccountResponseSubAccount) {
	c.SubAccount = subAccount
	c.require(createSubaccountResponseFieldSubAccount)
}

// SetAuthCredentials sets the AuthCredentials field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponse) SetAuthCredentials(authCredentials *CreateSubaccountResponseAuthCredentials) {
	c.AuthCredentials = authCredentials
	c.require(createSubaccountResponseFieldAuthCredentials)
}

// SetTokens sets the Tokens field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponse) SetTokens(tokens *CreateSubaccountResponseTokens) {
	c.Tokens = tokens
	c.require(createSubaccountResponseFieldTokens)
}

func (c *CreateSubaccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSubaccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSubaccountResponse) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSubaccountResponse) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSubaccountResponseAuthCredentialsFieldAuthID    = big.NewInt(1 << 0)
	createSubaccountResponseAuthCredentialsFieldAuthToken = big.NewInt(1 << 1)
)

type CreateSubaccountResponseAuthCredentials struct {
	AuthID    string `json:"auth_id" url:"auth_id"`
	AuthToken string `json:"auth_token" url:"auth_token"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSubaccountResponseAuthCredentials) GetAuthID() string {
	if c == nil {
		return ""
	}
	return c.AuthID
}

func (c *CreateSubaccountResponseAuthCredentials) GetAuthToken() string {
	if c == nil {
		return ""
	}
	return c.AuthToken
}

func (c *CreateSubaccountResponseAuthCredentials) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSubaccountResponseAuthCredentials) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseAuthCredentials) SetAuthID(authID string) {
	c.AuthID = authID
	c.require(createSubaccountResponseAuthCredentialsFieldAuthID)
}

// SetAuthToken sets the AuthToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseAuthCredentials) SetAuthToken(authToken string) {
	c.AuthToken = authToken
	c.require(createSubaccountResponseAuthCredentialsFieldAuthToken)
}

func (c *CreateSubaccountResponseAuthCredentials) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountResponseAuthCredentials
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSubaccountResponseAuthCredentials(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSubaccountResponseAuthCredentials) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountResponseAuthCredentials
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSubaccountResponseAuthCredentials) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSubaccountResponseSubAccountFieldName            = big.NewInt(1 << 0)
	createSubaccountResponseSubAccountFieldEmail           = big.NewInt(1 << 1)
	createSubaccountResponseSubAccountFieldPhone           = big.NewInt(1 << 2)
	createSubaccountResponseSubAccountFieldDescription     = big.NewInt(1 << 3)
	createSubaccountResponseSubAccountFieldPermissions     = big.NewInt(1 << 4)
	createSubaccountResponseSubAccountFieldRateLimit       = big.NewInt(1 << 5)
	createSubaccountResponseSubAccountFieldID              = big.NewInt(1 << 6)
	createSubaccountResponseSubAccountFieldParentAccountID = big.NewInt(1 << 7)
	createSubaccountResponseSubAccountFieldParentAuthID    = big.NewInt(1 << 8)
	createSubaccountResponseSubAccountFieldAuthID          = big.NewInt(1 << 9)
	createSubaccountResponseSubAccountFieldAuthToken       = big.NewInt(1 << 10)
	createSubaccountResponseSubAccountFieldApiId           = big.NewInt(1 << 11)
	createSubaccountResponseSubAccountFieldEmailVerified   = big.NewInt(1 << 12)
	createSubaccountResponseSubAccountFieldEnabled         = big.NewInt(1 << 13)
	createSubaccountResponseSubAccountFieldCreated         = big.NewInt(1 << 14)
	createSubaccountResponseSubAccountFieldModified        = big.NewInt(1 << 15)
	createSubaccountResponseSubAccountFieldIsActive        = big.NewInt(1 << 16)
	createSubaccountResponseSubAccountFieldCreatedAt       = big.NewInt(1 << 17)
	createSubaccountResponseSubAccountFieldUpdatedAt       = big.NewInt(1 << 18)
	createSubaccountResponseSubAccountFieldLastUsed        = big.NewInt(1 << 19)
	createSubaccountResponseSubAccountFieldAccount         = big.NewInt(1 << 20)
	createSubaccountResponseSubAccountFieldResourceURI     = big.NewInt(1 << 21)
)

type CreateSubaccountResponseSubAccount struct {
	Name            string `json:"name" url:"name"`
	Email           any    `json:"email,omitempty" url:"email,omitempty"`
	Phone           any    `json:"phone,omitempty" url:"phone,omitempty"`
	Description     any    `json:"description,omitempty" url:"description,omitempty"`
	Permissions     any    `json:"permissions,omitempty" url:"permissions,omitempty"`
	RateLimit       int    `json:"rate_limit" url:"rate_limit"`
	ID              string `json:"id" url:"id"`
	ParentAccountID string `json:"parent_account_id" url:"parent_account_id"`
	ParentAuthID    string `json:"parent_auth_id" url:"parent_auth_id"`
	AuthID          string `json:"auth_id" url:"auth_id"`
	AuthToken       string `json:"auth_token" url:"auth_token"`
	ApiId           string `json:"api_id" url:"api_id"`
	EmailVerified   bool   `json:"email_verified" url:"email_verified"`
	Enabled         bool   `json:"enabled" url:"enabled"`
	Created         string `json:"created" url:"created"`
	Modified        string `json:"modified" url:"modified"`
	IsActive        bool   `json:"is_active" url:"is_active"`
	CreatedAt       string `json:"created_at" url:"created_at"`
	UpdatedAt       string `json:"updated_at" url:"updated_at"`
	LastUsed        any    `json:"last_used,omitempty" url:"last_used,omitempty"`
	Account         string `json:"account" url:"account"`
	ResourceURI     string `json:"resource_uri" url:"resource_uri"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSubaccountResponseSubAccount) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateSubaccountResponseSubAccount) GetEmail() any {
	if c == nil {
		return nil
	}
	return c.Email
}

func (c *CreateSubaccountResponseSubAccount) GetPhone() any {
	if c == nil {
		return nil
	}
	return c.Phone
}

func (c *CreateSubaccountResponseSubAccount) GetDescription() any {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CreateSubaccountResponseSubAccount) GetPermissions() any {
	if c == nil {
		return nil
	}
	return c.Permissions
}

func (c *CreateSubaccountResponseSubAccount) GetRateLimit() int {
	if c == nil {
		return 0
	}
	return c.RateLimit
}

func (c *CreateSubaccountResponseSubAccount) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateSubaccountResponseSubAccount) GetParentAccountID() string {
	if c == nil {
		return ""
	}
	return c.ParentAccountID
}

func (c *CreateSubaccountResponseSubAccount) GetParentAuthID() string {
	if c == nil {
		return ""
	}
	return c.ParentAuthID
}

func (c *CreateSubaccountResponseSubAccount) GetAuthID() string {
	if c == nil {
		return ""
	}
	return c.AuthID
}

func (c *CreateSubaccountResponseSubAccount) GetAuthToken() string {
	if c == nil {
		return ""
	}
	return c.AuthToken
}

func (c *CreateSubaccountResponseSubAccount) GetApiId() string {
	if c == nil {
		return ""
	}
	return c.ApiId
}

func (c *CreateSubaccountResponseSubAccount) GetEmailVerified() bool {
	if c == nil {
		return false
	}
	return c.EmailVerified
}

func (c *CreateSubaccountResponseSubAccount) GetEnabled() bool {
	if c == nil {
		return false
	}
	return c.Enabled
}

func (c *CreateSubaccountResponseSubAccount) GetCreated() string {
	if c == nil {
		return ""
	}
	return c.Created
}

func (c *CreateSubaccountResponseSubAccount) GetModified() string {
	if c == nil {
		return ""
	}
	return c.Modified
}

func (c *CreateSubaccountResponseSubAccount) GetIsActive() bool {
	if c == nil {
		return false
	}
	return c.IsActive
}

func (c *CreateSubaccountResponseSubAccount) GetCreatedAt() string {
	if c == nil {
		return ""
	}
	return c.CreatedAt
}

func (c *CreateSubaccountResponseSubAccount) GetUpdatedAt() string {
	if c == nil {
		return ""
	}
	return c.UpdatedAt
}

func (c *CreateSubaccountResponseSubAccount) GetLastUsed() any {
	if c == nil {
		return nil
	}
	return c.LastUsed
}

func (c *CreateSubaccountResponseSubAccount) GetAccount() string {
	if c == nil {
		return ""
	}
	return c.Account
}

func (c *CreateSubaccountResponseSubAccount) GetResourceURI() string {
	if c == nil {
		return ""
	}
	return c.ResourceURI
}

func (c *CreateSubaccountResponseSubAccount) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSubaccountResponseSubAccount) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetName(name string) {
	c.Name = name
	c.require(createSubaccountResponseSubAccountFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetEmail(email any) {
	c.Email = email
	c.require(createSubaccountResponseSubAccountFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetPhone(phone any) {
	c.Phone = phone
	c.require(createSubaccountResponseSubAccountFieldPhone)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetDescription(description any) {
	c.Description = description
	c.require(createSubaccountResponseSubAccountFieldDescription)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetPermissions(permissions any) {
	c.Permissions = permissions
	c.require(createSubaccountResponseSubAccountFieldPermissions)
}

// SetRateLimit sets the RateLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetRateLimit(rateLimit int) {
	c.RateLimit = rateLimit
	c.require(createSubaccountResponseSubAccountFieldRateLimit)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetID(id string) {
	c.ID = id
	c.require(createSubaccountResponseSubAccountFieldID)
}

// SetParentAccountID sets the ParentAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetParentAccountID(parentAccountID string) {
	c.ParentAccountID = parentAccountID
	c.require(createSubaccountResponseSubAccountFieldParentAccountID)
}

// SetParentAuthID sets the ParentAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetParentAuthID(parentAuthID string) {
	c.ParentAuthID = parentAuthID
	c.require(createSubaccountResponseSubAccountFieldParentAuthID)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetAuthID(authID string) {
	c.AuthID = authID
	c.require(createSubaccountResponseSubAccountFieldAuthID)
}

// SetAuthToken sets the AuthToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetAuthToken(authToken string) {
	c.AuthToken = authToken
	c.require(createSubaccountResponseSubAccountFieldAuthToken)
}

// SetApiId sets the ApiId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetApiId(apiId string) {
	c.ApiId = apiId
	c.require(createSubaccountResponseSubAccountFieldApiId)
}

// SetEmailVerified sets the EmailVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetEmailVerified(emailVerified bool) {
	c.EmailVerified = emailVerified
	c.require(createSubaccountResponseSubAccountFieldEmailVerified)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetEnabled(enabled bool) {
	c.Enabled = enabled
	c.require(createSubaccountResponseSubAccountFieldEnabled)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetCreated(created string) {
	c.Created = created
	c.require(createSubaccountResponseSubAccountFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetModified(modified string) {
	c.Modified = modified
	c.require(createSubaccountResponseSubAccountFieldModified)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetIsActive(isActive bool) {
	c.IsActive = isActive
	c.require(createSubaccountResponseSubAccountFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetCreatedAt(createdAt string) {
	c.CreatedAt = createdAt
	c.require(createSubaccountResponseSubAccountFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetUpdatedAt(updatedAt string) {
	c.UpdatedAt = updatedAt
	c.require(createSubaccountResponseSubAccountFieldUpdatedAt)
}

// SetLastUsed sets the LastUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetLastUsed(lastUsed any) {
	c.LastUsed = lastUsed
	c.require(createSubaccountResponseSubAccountFieldLastUsed)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetAccount(account string) {
	c.Account = account
	c.require(createSubaccountResponseSubAccountFieldAccount)
}

// SetResourceURI sets the ResourceURI field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseSubAccount) SetResourceURI(resourceURI string) {
	c.ResourceURI = resourceURI
	c.require(createSubaccountResponseSubAccountFieldResourceURI)
}

func (c *CreateSubaccountResponseSubAccount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountResponseSubAccount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSubaccountResponseSubAccount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSubaccountResponseSubAccount) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountResponseSubAccount
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSubaccountResponseSubAccount) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createSubaccountResponseTokensFieldAccessToken  = big.NewInt(1 << 0)
	createSubaccountResponseTokensFieldRefreshToken = big.NewInt(1 << 1)
	createSubaccountResponseTokensFieldTokenType    = big.NewInt(1 << 2)
	createSubaccountResponseTokensFieldExpiresIn    = big.NewInt(1 << 3)
)

type CreateSubaccountResponseTokens struct {
	AccessToken  string `json:"access_token" url:"access_token"`
	RefreshToken string `json:"refresh_token" url:"refresh_token"`
	TokenType    string `json:"token_type" url:"token_type"`
	ExpiresIn    int    `json:"expires_in" url:"expires_in"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateSubaccountResponseTokens) GetAccessToken() string {
	if c == nil {
		return ""
	}
	return c.AccessToken
}

func (c *CreateSubaccountResponseTokens) GetRefreshToken() string {
	if c == nil {
		return ""
	}
	return c.RefreshToken
}

func (c *CreateSubaccountResponseTokens) GetTokenType() string {
	if c == nil {
		return ""
	}
	return c.TokenType
}

func (c *CreateSubaccountResponseTokens) GetExpiresIn() int {
	if c == nil {
		return 0
	}
	return c.ExpiresIn
}

func (c *CreateSubaccountResponseTokens) GetExtraProperties() map[string]interface{} {
	if c == nil {
		return nil
	}
	return c.extraProperties
}

func (c *CreateSubaccountResponseTokens) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccessToken sets the AccessToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseTokens) SetAccessToken(accessToken string) {
	c.AccessToken = accessToken
	c.require(createSubaccountResponseTokensFieldAccessToken)
}

// SetRefreshToken sets the RefreshToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseTokens) SetRefreshToken(refreshToken string) {
	c.RefreshToken = refreshToken
	c.require(createSubaccountResponseTokensFieldRefreshToken)
}

// SetTokenType sets the TokenType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseTokens) SetTokenType(tokenType string) {
	c.TokenType = tokenType
	c.require(createSubaccountResponseTokensFieldTokenType)
}

// SetExpiresIn sets the ExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountResponseTokens) SetExpiresIn(expiresIn int) {
	c.ExpiresIn = expiresIn
	c.require(createSubaccountResponseTokensFieldExpiresIn)
}

func (c *CreateSubaccountResponseTokens) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountResponseTokens
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateSubaccountResponseTokens(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateSubaccountResponseTokens) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountResponseTokens
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateSubaccountResponseTokens) String() string {
	if c == nil {
		return "<nil>"
	}
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	deleteSubaccountResponseFieldMessage = big.NewInt(1 << 0)
)

type DeleteSubaccountResponse struct {
	Message string `json:"message" url:"message"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (d *DeleteSubaccountResponse) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

func (d *DeleteSubaccountResponse) GetExtraProperties() map[string]interface{} {
	if d == nil {
		return nil
	}
	return d.extraProperties
}

func (d *DeleteSubaccountResponse) require(field *big.Int) {
	if d.explicitFields == nil {
		d.explicitFields = big.NewInt(0)
	}
	d.explicitFields.Or(d.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (d *DeleteSubaccountResponse) SetMessage(message string) {
	d.Message = message
	d.require(deleteSubaccountResponseFieldMessage)
}

func (d *DeleteSubaccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler DeleteSubaccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DeleteSubaccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *d)
	if err != nil {
		return err
	}
	d.extraProperties = extraProperties
	d.rawJSON = json.RawMessage(data)
	return nil
}

func (d *DeleteSubaccountResponse) MarshalJSON() ([]byte, error) {
	type embed DeleteSubaccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*d),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, d.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (d *DeleteSubaccountResponse) String() string {
	if d == nil {
		return "<nil>"
	}
	if len(d.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(d.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

var (
	listSubaccountsResponseFieldSubAccounts = big.NewInt(1 << 0)
	listSubaccountsResponseFieldTotal       = big.NewInt(1 << 1)
	listSubaccountsResponseFieldPage        = big.NewInt(1 << 2)
	listSubaccountsResponseFieldSize        = big.NewInt(1 << 3)
)

type ListSubaccountsResponse struct {
	SubAccounts []*ListSubaccountsResponseSubAccountsItem `json:"sub_accounts" url:"sub_accounts"`
	Total       int                                       `json:"total" url:"total"`
	Page        int                                       `json:"page" url:"page"`
	Size        int                                       `json:"size" url:"size"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSubaccountsResponse) GetSubAccounts() []*ListSubaccountsResponseSubAccountsItem {
	if l == nil {
		return nil
	}
	return l.SubAccounts
}

func (l *ListSubaccountsResponse) GetTotal() int {
	if l == nil {
		return 0
	}
	return l.Total
}

func (l *ListSubaccountsResponse) GetPage() int {
	if l == nil {
		return 0
	}
	return l.Page
}

func (l *ListSubaccountsResponse) GetSize() int {
	if l == nil {
		return 0
	}
	return l.Size
}

func (l *ListSubaccountsResponse) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSubaccountsResponse) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetSubAccounts sets the SubAccounts field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponse) SetSubAccounts(subAccounts []*ListSubaccountsResponseSubAccountsItem) {
	l.SubAccounts = subAccounts
	l.require(listSubaccountsResponseFieldSubAccounts)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponse) SetTotal(total int) {
	l.Total = total
	l.require(listSubaccountsResponseFieldTotal)
}

// SetPage sets the Page field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponse) SetPage(page int) {
	l.Page = page
	l.require(listSubaccountsResponseFieldPage)
}

// SetSize sets the Size field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponse) SetSize(size int) {
	l.Size = size
	l.require(listSubaccountsResponseFieldSize)
}

func (l *ListSubaccountsResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSubaccountsResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSubaccountsResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSubaccountsResponse) MarshalJSON() ([]byte, error) {
	type embed ListSubaccountsResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSubaccountsResponse) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	listSubaccountsResponseSubAccountsItemFieldName            = big.NewInt(1 << 0)
	listSubaccountsResponseSubAccountsItemFieldEmail           = big.NewInt(1 << 1)
	listSubaccountsResponseSubAccountsItemFieldPhone           = big.NewInt(1 << 2)
	listSubaccountsResponseSubAccountsItemFieldDescription     = big.NewInt(1 << 3)
	listSubaccountsResponseSubAccountsItemFieldPermissions     = big.NewInt(1 << 4)
	listSubaccountsResponseSubAccountsItemFieldRateLimit       = big.NewInt(1 << 5)
	listSubaccountsResponseSubAccountsItemFieldID              = big.NewInt(1 << 6)
	listSubaccountsResponseSubAccountsItemFieldParentAccountID = big.NewInt(1 << 7)
	listSubaccountsResponseSubAccountsItemFieldParentAuthID    = big.NewInt(1 << 8)
	listSubaccountsResponseSubAccountsItemFieldAuthID          = big.NewInt(1 << 9)
	listSubaccountsResponseSubAccountsItemFieldAuthToken       = big.NewInt(1 << 10)
	listSubaccountsResponseSubAccountsItemFieldApiId           = big.NewInt(1 << 11)
	listSubaccountsResponseSubAccountsItemFieldEmailVerified   = big.NewInt(1 << 12)
	listSubaccountsResponseSubAccountsItemFieldEnabled         = big.NewInt(1 << 13)
	listSubaccountsResponseSubAccountsItemFieldCreated         = big.NewInt(1 << 14)
	listSubaccountsResponseSubAccountsItemFieldModified        = big.NewInt(1 << 15)
	listSubaccountsResponseSubAccountsItemFieldIsActive        = big.NewInt(1 << 16)
	listSubaccountsResponseSubAccountsItemFieldCreatedAt       = big.NewInt(1 << 17)
	listSubaccountsResponseSubAccountsItemFieldUpdatedAt       = big.NewInt(1 << 18)
	listSubaccountsResponseSubAccountsItemFieldLastUsed        = big.NewInt(1 << 19)
	listSubaccountsResponseSubAccountsItemFieldAccount         = big.NewInt(1 << 20)
	listSubaccountsResponseSubAccountsItemFieldResourceURI     = big.NewInt(1 << 21)
)

type ListSubaccountsResponseSubAccountsItem struct {
	Name            string                                             `json:"name" url:"name"`
	Email           *string                                            `json:"email,omitempty" url:"email,omitempty"`
	Phone           any                                                `json:"phone,omitempty" url:"phone,omitempty"`
	Description     any                                                `json:"description,omitempty" url:"description,omitempty"`
	Permissions     *ListSubaccountsResponseSubAccountsItemPermissions `json:"permissions" url:"permissions"`
	RateLimit       int                                                `json:"rate_limit" url:"rate_limit"`
	ID              string                                             `json:"id" url:"id"`
	ParentAccountID string                                             `json:"parent_account_id" url:"parent_account_id"`
	ParentAuthID    string                                             `json:"parent_auth_id" url:"parent_auth_id"`
	AuthID          string                                             `json:"auth_id" url:"auth_id"`
	AuthToken       string                                             `json:"auth_token" url:"auth_token"`
	ApiId           string                                             `json:"api_id" url:"api_id"`
	EmailVerified   bool                                               `json:"email_verified" url:"email_verified"`
	Enabled         bool                                               `json:"enabled" url:"enabled"`
	Created         string                                             `json:"created" url:"created"`
	Modified        string                                             `json:"modified" url:"modified"`
	IsActive        bool                                               `json:"is_active" url:"is_active"`
	CreatedAt       string                                             `json:"created_at" url:"created_at"`
	UpdatedAt       string                                             `json:"updated_at" url:"updated_at"`
	LastUsed        *string                                            `json:"last_used,omitempty" url:"last_used,omitempty"`
	Account         string                                             `json:"account" url:"account"`
	ResourceURI     string                                             `json:"resource_uri" url:"resource_uri"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSubaccountsResponseSubAccountsItem) GetName() string {
	if l == nil {
		return ""
	}
	return l.Name
}

func (l *ListSubaccountsResponseSubAccountsItem) GetEmail() *string {
	if l == nil {
		return nil
	}
	return l.Email
}

func (l *ListSubaccountsResponseSubAccountsItem) GetPhone() any {
	if l == nil {
		return nil
	}
	return l.Phone
}

func (l *ListSubaccountsResponseSubAccountsItem) GetDescription() any {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *ListSubaccountsResponseSubAccountsItem) GetPermissions() *ListSubaccountsResponseSubAccountsItemPermissions {
	if l == nil {
		return nil
	}
	return l.Permissions
}

func (l *ListSubaccountsResponseSubAccountsItem) GetRateLimit() int {
	if l == nil {
		return 0
	}
	return l.RateLimit
}

func (l *ListSubaccountsResponseSubAccountsItem) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *ListSubaccountsResponseSubAccountsItem) GetParentAccountID() string {
	if l == nil {
		return ""
	}
	return l.ParentAccountID
}

func (l *ListSubaccountsResponseSubAccountsItem) GetParentAuthID() string {
	if l == nil {
		return ""
	}
	return l.ParentAuthID
}

func (l *ListSubaccountsResponseSubAccountsItem) GetAuthID() string {
	if l == nil {
		return ""
	}
	return l.AuthID
}

func (l *ListSubaccountsResponseSubAccountsItem) GetAuthToken() string {
	if l == nil {
		return ""
	}
	return l.AuthToken
}

func (l *ListSubaccountsResponseSubAccountsItem) GetApiId() string {
	if l == nil {
		return ""
	}
	return l.ApiId
}

func (l *ListSubaccountsResponseSubAccountsItem) GetEmailVerified() bool {
	if l == nil {
		return false
	}
	return l.EmailVerified
}

func (l *ListSubaccountsResponseSubAccountsItem) GetEnabled() bool {
	if l == nil {
		return false
	}
	return l.Enabled
}

func (l *ListSubaccountsResponseSubAccountsItem) GetCreated() string {
	if l == nil {
		return ""
	}
	return l.Created
}

func (l *ListSubaccountsResponseSubAccountsItem) GetModified() string {
	if l == nil {
		return ""
	}
	return l.Modified
}

func (l *ListSubaccountsResponseSubAccountsItem) GetIsActive() bool {
	if l == nil {
		return false
	}
	return l.IsActive
}

func (l *ListSubaccountsResponseSubAccountsItem) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *ListSubaccountsResponseSubAccountsItem) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *ListSubaccountsResponseSubAccountsItem) GetLastUsed() *string {
	if l == nil {
		return nil
	}
	return l.LastUsed
}

func (l *ListSubaccountsResponseSubAccountsItem) GetAccount() string {
	if l == nil {
		return ""
	}
	return l.Account
}

func (l *ListSubaccountsResponseSubAccountsItem) GetResourceURI() string {
	if l == nil {
		return ""
	}
	return l.ResourceURI
}

func (l *ListSubaccountsResponseSubAccountsItem) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSubaccountsResponseSubAccountsItem) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetName(name string) {
	l.Name = name
	l.require(listSubaccountsResponseSubAccountsItemFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetEmail(email *string) {
	l.Email = email
	l.require(listSubaccountsResponseSubAccountsItemFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetPhone(phone any) {
	l.Phone = phone
	l.require(listSubaccountsResponseSubAccountsItemFieldPhone)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetDescription(description any) {
	l.Description = description
	l.require(listSubaccountsResponseSubAccountsItemFieldDescription)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetPermissions(permissions *ListSubaccountsResponseSubAccountsItemPermissions) {
	l.Permissions = permissions
	l.require(listSubaccountsResponseSubAccountsItemFieldPermissions)
}

// SetRateLimit sets the RateLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetRateLimit(rateLimit int) {
	l.RateLimit = rateLimit
	l.require(listSubaccountsResponseSubAccountsItemFieldRateLimit)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetID(id string) {
	l.ID = id
	l.require(listSubaccountsResponseSubAccountsItemFieldID)
}

// SetParentAccountID sets the ParentAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetParentAccountID(parentAccountID string) {
	l.ParentAccountID = parentAccountID
	l.require(listSubaccountsResponseSubAccountsItemFieldParentAccountID)
}

// SetParentAuthID sets the ParentAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetParentAuthID(parentAuthID string) {
	l.ParentAuthID = parentAuthID
	l.require(listSubaccountsResponseSubAccountsItemFieldParentAuthID)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetAuthID(authID string) {
	l.AuthID = authID
	l.require(listSubaccountsResponseSubAccountsItemFieldAuthID)
}

// SetAuthToken sets the AuthToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetAuthToken(authToken string) {
	l.AuthToken = authToken
	l.require(listSubaccountsResponseSubAccountsItemFieldAuthToken)
}

// SetApiId sets the ApiId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetApiId(apiId string) {
	l.ApiId = apiId
	l.require(listSubaccountsResponseSubAccountsItemFieldApiId)
}

// SetEmailVerified sets the EmailVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetEmailVerified(emailVerified bool) {
	l.EmailVerified = emailVerified
	l.require(listSubaccountsResponseSubAccountsItemFieldEmailVerified)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetEnabled(enabled bool) {
	l.Enabled = enabled
	l.require(listSubaccountsResponseSubAccountsItemFieldEnabled)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetCreated(created string) {
	l.Created = created
	l.require(listSubaccountsResponseSubAccountsItemFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetModified(modified string) {
	l.Modified = modified
	l.require(listSubaccountsResponseSubAccountsItemFieldModified)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetIsActive(isActive bool) {
	l.IsActive = isActive
	l.require(listSubaccountsResponseSubAccountsItemFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetCreatedAt(createdAt string) {
	l.CreatedAt = createdAt
	l.require(listSubaccountsResponseSubAccountsItemFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetUpdatedAt(updatedAt string) {
	l.UpdatedAt = updatedAt
	l.require(listSubaccountsResponseSubAccountsItemFieldUpdatedAt)
}

// SetLastUsed sets the LastUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetLastUsed(lastUsed *string) {
	l.LastUsed = lastUsed
	l.require(listSubaccountsResponseSubAccountsItemFieldLastUsed)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetAccount(account string) {
	l.Account = account
	l.require(listSubaccountsResponseSubAccountsItemFieldAccount)
}

// SetResourceURI sets the ResourceURI field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItem) SetResourceURI(resourceURI string) {
	l.ResourceURI = resourceURI
	l.require(listSubaccountsResponseSubAccountsItemFieldResourceURI)
}

func (l *ListSubaccountsResponseSubAccountsItem) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSubaccountsResponseSubAccountsItem
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSubaccountsResponseSubAccountsItem(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSubaccountsResponseSubAccountsItem) MarshalJSON() ([]byte, error) {
	type embed ListSubaccountsResponseSubAccountsItem
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSubaccountsResponseSubAccountsItem) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

type ListSubaccountsResponseSubAccountsItemPermissions struct {
	UnknownOptional                                        any
	ListSubaccountsResponseSubAccountsItemPermissionsCalls *ListSubaccountsResponseSubAccountsItemPermissionsCalls

	typ string
}

func (l *ListSubaccountsResponseSubAccountsItemPermissions) GetUnknownOptional() any {
	if l == nil {
		return nil
	}
	return l.UnknownOptional
}

func (l *ListSubaccountsResponseSubAccountsItemPermissions) GetListSubaccountsResponseSubAccountsItemPermissionsCalls() *ListSubaccountsResponseSubAccountsItemPermissionsCalls {
	if l == nil {
		return nil
	}
	return l.ListSubaccountsResponseSubAccountsItemPermissionsCalls
}

func (l *ListSubaccountsResponseSubAccountsItemPermissions) UnmarshalJSON(data []byte) error {
	var valueUnknownOptional any
	if err := json.Unmarshal(data, &valueUnknownOptional); err == nil {
		l.typ = "UnknownOptional"
		l.UnknownOptional = valueUnknownOptional
		return nil
	}
	valueListSubaccountsResponseSubAccountsItemPermissionsCalls := new(ListSubaccountsResponseSubAccountsItemPermissionsCalls)
	if err := json.Unmarshal(data, &valueListSubaccountsResponseSubAccountsItemPermissionsCalls); err == nil {
		l.typ = "ListSubaccountsResponseSubAccountsItemPermissionsCalls"
		l.ListSubaccountsResponseSubAccountsItemPermissionsCalls = valueListSubaccountsResponseSubAccountsItemPermissionsCalls
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, l)
}

func (l ListSubaccountsResponseSubAccountsItemPermissions) MarshalJSON() ([]byte, error) {
	if l.typ == "UnknownOptional" || l.UnknownOptional != nil {
		return json.Marshal(l.UnknownOptional)
	}
	if l.typ == "ListSubaccountsResponseSubAccountsItemPermissionsCalls" || l.ListSubaccountsResponseSubAccountsItemPermissionsCalls != nil {
		return json.Marshal(l.ListSubaccountsResponseSubAccountsItemPermissionsCalls)
	}
	return nil, fmt.Errorf("type %T does not include a non-empty union type", l)
}

type ListSubaccountsResponseSubAccountsItemPermissionsVisitor interface {
	VisitUnknownOptional(any) error
	VisitListSubaccountsResponseSubAccountsItemPermissionsCalls(*ListSubaccountsResponseSubAccountsItemPermissionsCalls) error
}

func (l *ListSubaccountsResponseSubAccountsItemPermissions) Accept(visitor ListSubaccountsResponseSubAccountsItemPermissionsVisitor) error {
	if l.typ == "UnknownOptional" || l.UnknownOptional != nil {
		return visitor.VisitUnknownOptional(l.UnknownOptional)
	}
	if l.typ == "ListSubaccountsResponseSubAccountsItemPermissionsCalls" || l.ListSubaccountsResponseSubAccountsItemPermissionsCalls != nil {
		return visitor.VisitListSubaccountsResponseSubAccountsItemPermissionsCalls(l.ListSubaccountsResponseSubAccountsItemPermissionsCalls)
	}
	return fmt.Errorf("type %T does not include a non-empty union type", l)
}

var (
	listSubaccountsResponseSubAccountsItemPermissionsCallsFieldCdr   = big.NewInt(1 << 0)
	listSubaccountsResponseSubAccountsItemPermissionsCallsFieldCalls = big.NewInt(1 << 1)
)

type ListSubaccountsResponseSubAccountsItemPermissionsCalls struct {
	Cdr   *bool `json:"cdr,omitempty" url:"cdr,omitempty"`
	Calls *bool `json:"calls,omitempty" url:"calls,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) GetCdr() *bool {
	if l == nil {
		return nil
	}
	return l.Cdr
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) GetCalls() *bool {
	if l == nil {
		return nil
	}
	return l.Calls
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) GetExtraProperties() map[string]interface{} {
	if l == nil {
		return nil
	}
	return l.extraProperties
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) require(field *big.Int) {
	if l.explicitFields == nil {
		l.explicitFields = big.NewInt(0)
	}
	l.explicitFields.Or(l.explicitFields, field)
}

// SetCdr sets the Cdr field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) SetCdr(cdr *bool) {
	l.Cdr = cdr
	l.require(listSubaccountsResponseSubAccountsItemPermissionsCallsFieldCdr)
}

// SetCalls sets the Calls field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) SetCalls(calls *bool) {
	l.Calls = calls
	l.require(listSubaccountsResponseSubAccountsItemPermissionsCallsFieldCalls)
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) UnmarshalJSON(data []byte) error {
	type unmarshaler ListSubaccountsResponseSubAccountsItemPermissionsCalls
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*l = ListSubaccountsResponseSubAccountsItemPermissionsCalls(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *l)
	if err != nil {
		return err
	}
	l.extraProperties = extraProperties
	l.rawJSON = json.RawMessage(data)
	return nil
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) MarshalJSON() ([]byte, error) {
	type embed ListSubaccountsResponseSubAccountsItemPermissionsCalls
	var marshaler = struct {
		embed
	}{
		embed: embed(*l),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, l.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (l *ListSubaccountsResponseSubAccountsItemPermissionsCalls) String() string {
	if l == nil {
		return "<nil>"
	}
	if len(l.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(l.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(l); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", l)
}

var (
	retrieveSubaccountResponseFieldName            = big.NewInt(1 << 0)
	retrieveSubaccountResponseFieldEmail           = big.NewInt(1 << 1)
	retrieveSubaccountResponseFieldPhone           = big.NewInt(1 << 2)
	retrieveSubaccountResponseFieldDescription     = big.NewInt(1 << 3)
	retrieveSubaccountResponseFieldPermissions     = big.NewInt(1 << 4)
	retrieveSubaccountResponseFieldRateLimit       = big.NewInt(1 << 5)
	retrieveSubaccountResponseFieldID              = big.NewInt(1 << 6)
	retrieveSubaccountResponseFieldParentAccountID = big.NewInt(1 << 7)
	retrieveSubaccountResponseFieldParentAuthID    = big.NewInt(1 << 8)
	retrieveSubaccountResponseFieldAuthID          = big.NewInt(1 << 9)
	retrieveSubaccountResponseFieldAuthToken       = big.NewInt(1 << 10)
	retrieveSubaccountResponseFieldApiId           = big.NewInt(1 << 11)
	retrieveSubaccountResponseFieldEmailVerified   = big.NewInt(1 << 12)
	retrieveSubaccountResponseFieldEnabled         = big.NewInt(1 << 13)
	retrieveSubaccountResponseFieldCreated         = big.NewInt(1 << 14)
	retrieveSubaccountResponseFieldModified        = big.NewInt(1 << 15)
	retrieveSubaccountResponseFieldIsActive        = big.NewInt(1 << 16)
	retrieveSubaccountResponseFieldCreatedAt       = big.NewInt(1 << 17)
	retrieveSubaccountResponseFieldUpdatedAt       = big.NewInt(1 << 18)
	retrieveSubaccountResponseFieldLastUsed        = big.NewInt(1 << 19)
	retrieveSubaccountResponseFieldAccount         = big.NewInt(1 << 20)
	retrieveSubaccountResponseFieldResourceURI     = big.NewInt(1 << 21)
)

type RetrieveSubaccountResponse struct {
	Name            string `json:"name" url:"name"`
	Email           any    `json:"email,omitempty" url:"email,omitempty"`
	Phone           any    `json:"phone,omitempty" url:"phone,omitempty"`
	Description     any    `json:"description,omitempty" url:"description,omitempty"`
	Permissions     any    `json:"permissions,omitempty" url:"permissions,omitempty"`
	RateLimit       int    `json:"rate_limit" url:"rate_limit"`
	ID              string `json:"id" url:"id"`
	ParentAccountID string `json:"parent_account_id" url:"parent_account_id"`
	ParentAuthID    string `json:"parent_auth_id" url:"parent_auth_id"`
	AuthID          string `json:"auth_id" url:"auth_id"`
	AuthToken       string `json:"auth_token" url:"auth_token"`
	ApiId           string `json:"api_id" url:"api_id"`
	EmailVerified   bool   `json:"email_verified" url:"email_verified"`
	Enabled         bool   `json:"enabled" url:"enabled"`
	Created         string `json:"created" url:"created"`
	Modified        string `json:"modified" url:"modified"`
	IsActive        bool   `json:"is_active" url:"is_active"`
	CreatedAt       string `json:"created_at" url:"created_at"`
	UpdatedAt       string `json:"updated_at" url:"updated_at"`
	LastUsed        any    `json:"last_used,omitempty" url:"last_used,omitempty"`
	Account         string `json:"account" url:"account"`
	ResourceURI     string `json:"resource_uri" url:"resource_uri"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RetrieveSubaccountResponse) GetName() string {
	if r == nil {
		return ""
	}
	return r.Name
}

func (r *RetrieveSubaccountResponse) GetEmail() any {
	if r == nil {
		return nil
	}
	return r.Email
}

func (r *RetrieveSubaccountResponse) GetPhone() any {
	if r == nil {
		return nil
	}
	return r.Phone
}

func (r *RetrieveSubaccountResponse) GetDescription() any {
	if r == nil {
		return nil
	}
	return r.Description
}

func (r *RetrieveSubaccountResponse) GetPermissions() any {
	if r == nil {
		return nil
	}
	return r.Permissions
}

func (r *RetrieveSubaccountResponse) GetRateLimit() int {
	if r == nil {
		return 0
	}
	return r.RateLimit
}

func (r *RetrieveSubaccountResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RetrieveSubaccountResponse) GetParentAccountID() string {
	if r == nil {
		return ""
	}
	return r.ParentAccountID
}

func (r *RetrieveSubaccountResponse) GetParentAuthID() string {
	if r == nil {
		return ""
	}
	return r.ParentAuthID
}

func (r *RetrieveSubaccountResponse) GetAuthID() string {
	if r == nil {
		return ""
	}
	return r.AuthID
}

func (r *RetrieveSubaccountResponse) GetAuthToken() string {
	if r == nil {
		return ""
	}
	return r.AuthToken
}

func (r *RetrieveSubaccountResponse) GetApiId() string {
	if r == nil {
		return ""
	}
	return r.ApiId
}

func (r *RetrieveSubaccountResponse) GetEmailVerified() bool {
	if r == nil {
		return false
	}
	return r.EmailVerified
}

func (r *RetrieveSubaccountResponse) GetEnabled() bool {
	if r == nil {
		return false
	}
	return r.Enabled
}

func (r *RetrieveSubaccountResponse) GetCreated() string {
	if r == nil {
		return ""
	}
	return r.Created
}

func (r *RetrieveSubaccountResponse) GetModified() string {
	if r == nil {
		return ""
	}
	return r.Modified
}

func (r *RetrieveSubaccountResponse) GetIsActive() bool {
	if r == nil {
		return false
	}
	return r.IsActive
}

func (r *RetrieveSubaccountResponse) GetCreatedAt() string {
	if r == nil {
		return ""
	}
	return r.CreatedAt
}

func (r *RetrieveSubaccountResponse) GetUpdatedAt() string {
	if r == nil {
		return ""
	}
	return r.UpdatedAt
}

func (r *RetrieveSubaccountResponse) GetLastUsed() any {
	if r == nil {
		return nil
	}
	return r.LastUsed
}

func (r *RetrieveSubaccountResponse) GetAccount() string {
	if r == nil {
		return ""
	}
	return r.Account
}

func (r *RetrieveSubaccountResponse) GetResourceURI() string {
	if r == nil {
		return ""
	}
	return r.ResourceURI
}

func (r *RetrieveSubaccountResponse) GetExtraProperties() map[string]interface{} {
	if r == nil {
		return nil
	}
	return r.extraProperties
}

func (r *RetrieveSubaccountResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetName(name string) {
	r.Name = name
	r.require(retrieveSubaccountResponseFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetEmail(email any) {
	r.Email = email
	r.require(retrieveSubaccountResponseFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetPhone(phone any) {
	r.Phone = phone
	r.require(retrieveSubaccountResponseFieldPhone)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetDescription(description any) {
	r.Description = description
	r.require(retrieveSubaccountResponseFieldDescription)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetPermissions(permissions any) {
	r.Permissions = permissions
	r.require(retrieveSubaccountResponseFieldPermissions)
}

// SetRateLimit sets the RateLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetRateLimit(rateLimit int) {
	r.RateLimit = rateLimit
	r.require(retrieveSubaccountResponseFieldRateLimit)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetID(id string) {
	r.ID = id
	r.require(retrieveSubaccountResponseFieldID)
}

// SetParentAccountID sets the ParentAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetParentAccountID(parentAccountID string) {
	r.ParentAccountID = parentAccountID
	r.require(retrieveSubaccountResponseFieldParentAccountID)
}

// SetParentAuthID sets the ParentAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetParentAuthID(parentAuthID string) {
	r.ParentAuthID = parentAuthID
	r.require(retrieveSubaccountResponseFieldParentAuthID)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetAuthID(authID string) {
	r.AuthID = authID
	r.require(retrieveSubaccountResponseFieldAuthID)
}

// SetAuthToken sets the AuthToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetAuthToken(authToken string) {
	r.AuthToken = authToken
	r.require(retrieveSubaccountResponseFieldAuthToken)
}

// SetApiId sets the ApiId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetApiId(apiId string) {
	r.ApiId = apiId
	r.require(retrieveSubaccountResponseFieldApiId)
}

// SetEmailVerified sets the EmailVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetEmailVerified(emailVerified bool) {
	r.EmailVerified = emailVerified
	r.require(retrieveSubaccountResponseFieldEmailVerified)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetEnabled(enabled bool) {
	r.Enabled = enabled
	r.require(retrieveSubaccountResponseFieldEnabled)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetCreated(created string) {
	r.Created = created
	r.require(retrieveSubaccountResponseFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetModified(modified string) {
	r.Modified = modified
	r.require(retrieveSubaccountResponseFieldModified)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetIsActive(isActive bool) {
	r.IsActive = isActive
	r.require(retrieveSubaccountResponseFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetCreatedAt(createdAt string) {
	r.CreatedAt = createdAt
	r.require(retrieveSubaccountResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetUpdatedAt(updatedAt string) {
	r.UpdatedAt = updatedAt
	r.require(retrieveSubaccountResponseFieldUpdatedAt)
}

// SetLastUsed sets the LastUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetLastUsed(lastUsed any) {
	r.LastUsed = lastUsed
	r.require(retrieveSubaccountResponseFieldLastUsed)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetAccount(account string) {
	r.Account = account
	r.require(retrieveSubaccountResponseFieldAccount)
}

// SetResourceURI sets the ResourceURI field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RetrieveSubaccountResponse) SetResourceURI(resourceURI string) {
	r.ResourceURI = resourceURI
	r.require(retrieveSubaccountResponseFieldResourceURI)
}

func (r *RetrieveSubaccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RetrieveSubaccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RetrieveSubaccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RetrieveSubaccountResponse) MarshalJSON() ([]byte, error) {
	type embed RetrieveSubaccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RetrieveSubaccountResponse) String() string {
	if r == nil {
		return "<nil>"
	}
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

// Change the verification mode. Promoting to `customer_use` requires the sub-account to have an `email`.
type UpdateSubaccountRequestKycMode string

const (
	UpdateSubaccountRequestKycModePersonalUse UpdateSubaccountRequestKycMode = "personal_use"
	UpdateSubaccountRequestKycModeCustomerUse UpdateSubaccountRequestKycMode = "customer_use"
)

func NewUpdateSubaccountRequestKycModeFromString(s string) (UpdateSubaccountRequestKycMode, error) {
	switch s {
	case "personal_use":
		return UpdateSubaccountRequestKycModePersonalUse, nil
	case "customer_use":
		return UpdateSubaccountRequestKycModeCustomerUse, nil
	}
	var t UpdateSubaccountRequestKycMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (u UpdateSubaccountRequestKycMode) Ptr() *UpdateSubaccountRequestKycMode {
	return &u
}

var (
	updateSubaccountResponseFieldName            = big.NewInt(1 << 0)
	updateSubaccountResponseFieldEmail           = big.NewInt(1 << 1)
	updateSubaccountResponseFieldPhone           = big.NewInt(1 << 2)
	updateSubaccountResponseFieldDescription     = big.NewInt(1 << 3)
	updateSubaccountResponseFieldPermissions     = big.NewInt(1 << 4)
	updateSubaccountResponseFieldRateLimit       = big.NewInt(1 << 5)
	updateSubaccountResponseFieldID              = big.NewInt(1 << 6)
	updateSubaccountResponseFieldParentAccountID = big.NewInt(1 << 7)
	updateSubaccountResponseFieldParentAuthID    = big.NewInt(1 << 8)
	updateSubaccountResponseFieldAuthID          = big.NewInt(1 << 9)
	updateSubaccountResponseFieldAuthToken       = big.NewInt(1 << 10)
	updateSubaccountResponseFieldApiId           = big.NewInt(1 << 11)
	updateSubaccountResponseFieldEmailVerified   = big.NewInt(1 << 12)
	updateSubaccountResponseFieldEnabled         = big.NewInt(1 << 13)
	updateSubaccountResponseFieldCreated         = big.NewInt(1 << 14)
	updateSubaccountResponseFieldModified        = big.NewInt(1 << 15)
	updateSubaccountResponseFieldIsActive        = big.NewInt(1 << 16)
	updateSubaccountResponseFieldCreatedAt       = big.NewInt(1 << 17)
	updateSubaccountResponseFieldUpdatedAt       = big.NewInt(1 << 18)
	updateSubaccountResponseFieldLastUsed        = big.NewInt(1 << 19)
	updateSubaccountResponseFieldAccount         = big.NewInt(1 << 20)
	updateSubaccountResponseFieldResourceURI     = big.NewInt(1 << 21)
)

type UpdateSubaccountResponse struct {
	Name            string `json:"name" url:"name"`
	Email           any    `json:"email,omitempty" url:"email,omitempty"`
	Phone           any    `json:"phone,omitempty" url:"phone,omitempty"`
	Description     any    `json:"description,omitempty" url:"description,omitempty"`
	Permissions     any    `json:"permissions,omitempty" url:"permissions,omitempty"`
	RateLimit       int    `json:"rate_limit" url:"rate_limit"`
	ID              string `json:"id" url:"id"`
	ParentAccountID string `json:"parent_account_id" url:"parent_account_id"`
	ParentAuthID    string `json:"parent_auth_id" url:"parent_auth_id"`
	AuthID          string `json:"auth_id" url:"auth_id"`
	AuthToken       string `json:"auth_token" url:"auth_token"`
	ApiId           string `json:"api_id" url:"api_id"`
	EmailVerified   bool   `json:"email_verified" url:"email_verified"`
	Enabled         bool   `json:"enabled" url:"enabled"`
	Created         string `json:"created" url:"created"`
	Modified        string `json:"modified" url:"modified"`
	IsActive        bool   `json:"is_active" url:"is_active"`
	CreatedAt       string `json:"created_at" url:"created_at"`
	UpdatedAt       string `json:"updated_at" url:"updated_at"`
	LastUsed        any    `json:"last_used,omitempty" url:"last_used,omitempty"`
	Account         string `json:"account" url:"account"`
	ResourceURI     string `json:"resource_uri" url:"resource_uri"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (u *UpdateSubaccountResponse) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UpdateSubaccountResponse) GetEmail() any {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *UpdateSubaccountResponse) GetPhone() any {
	if u == nil {
		return nil
	}
	return u.Phone
}

func (u *UpdateSubaccountResponse) GetDescription() any {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateSubaccountResponse) GetPermissions() any {
	if u == nil {
		return nil
	}
	return u.Permissions
}

func (u *UpdateSubaccountResponse) GetRateLimit() int {
	if u == nil {
		return 0
	}
	return u.RateLimit
}

func (u *UpdateSubaccountResponse) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateSubaccountResponse) GetParentAccountID() string {
	if u == nil {
		return ""
	}
	return u.ParentAccountID
}

func (u *UpdateSubaccountResponse) GetParentAuthID() string {
	if u == nil {
		return ""
	}
	return u.ParentAuthID
}

func (u *UpdateSubaccountResponse) GetAuthID() string {
	if u == nil {
		return ""
	}
	return u.AuthID
}

func (u *UpdateSubaccountResponse) GetAuthToken() string {
	if u == nil {
		return ""
	}
	return u.AuthToken
}

func (u *UpdateSubaccountResponse) GetApiId() string {
	if u == nil {
		return ""
	}
	return u.ApiId
}

func (u *UpdateSubaccountResponse) GetEmailVerified() bool {
	if u == nil {
		return false
	}
	return u.EmailVerified
}

func (u *UpdateSubaccountResponse) GetEnabled() bool {
	if u == nil {
		return false
	}
	return u.Enabled
}

func (u *UpdateSubaccountResponse) GetCreated() string {
	if u == nil {
		return ""
	}
	return u.Created
}

func (u *UpdateSubaccountResponse) GetModified() string {
	if u == nil {
		return ""
	}
	return u.Modified
}

func (u *UpdateSubaccountResponse) GetIsActive() bool {
	if u == nil {
		return false
	}
	return u.IsActive
}

func (u *UpdateSubaccountResponse) GetCreatedAt() string {
	if u == nil {
		return ""
	}
	return u.CreatedAt
}

func (u *UpdateSubaccountResponse) GetUpdatedAt() string {
	if u == nil {
		return ""
	}
	return u.UpdatedAt
}

func (u *UpdateSubaccountResponse) GetLastUsed() any {
	if u == nil {
		return nil
	}
	return u.LastUsed
}

func (u *UpdateSubaccountResponse) GetAccount() string {
	if u == nil {
		return ""
	}
	return u.Account
}

func (u *UpdateSubaccountResponse) GetResourceURI() string {
	if u == nil {
		return ""
	}
	return u.ResourceURI
}

func (u *UpdateSubaccountResponse) GetExtraProperties() map[string]interface{} {
	if u == nil {
		return nil
	}
	return u.extraProperties
}

func (u *UpdateSubaccountResponse) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetName(name string) {
	u.Name = name
	u.require(updateSubaccountResponseFieldName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetEmail(email any) {
	u.Email = email
	u.require(updateSubaccountResponseFieldEmail)
}

// SetPhone sets the Phone field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetPhone(phone any) {
	u.Phone = phone
	u.require(updateSubaccountResponseFieldPhone)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetDescription(description any) {
	u.Description = description
	u.require(updateSubaccountResponseFieldDescription)
}

// SetPermissions sets the Permissions field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetPermissions(permissions any) {
	u.Permissions = permissions
	u.require(updateSubaccountResponseFieldPermissions)
}

// SetRateLimit sets the RateLimit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetRateLimit(rateLimit int) {
	u.RateLimit = rateLimit
	u.require(updateSubaccountResponseFieldRateLimit)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetID(id string) {
	u.ID = id
	u.require(updateSubaccountResponseFieldID)
}

// SetParentAccountID sets the ParentAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetParentAccountID(parentAccountID string) {
	u.ParentAccountID = parentAccountID
	u.require(updateSubaccountResponseFieldParentAccountID)
}

// SetParentAuthID sets the ParentAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetParentAuthID(parentAuthID string) {
	u.ParentAuthID = parentAuthID
	u.require(updateSubaccountResponseFieldParentAuthID)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetAuthID(authID string) {
	u.AuthID = authID
	u.require(updateSubaccountResponseFieldAuthID)
}

// SetAuthToken sets the AuthToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetAuthToken(authToken string) {
	u.AuthToken = authToken
	u.require(updateSubaccountResponseFieldAuthToken)
}

// SetApiId sets the ApiId field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetApiId(apiId string) {
	u.ApiId = apiId
	u.require(updateSubaccountResponseFieldApiId)
}

// SetEmailVerified sets the EmailVerified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetEmailVerified(emailVerified bool) {
	u.EmailVerified = emailVerified
	u.require(updateSubaccountResponseFieldEmailVerified)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetEnabled(enabled bool) {
	u.Enabled = enabled
	u.require(updateSubaccountResponseFieldEnabled)
}

// SetCreated sets the Created field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetCreated(created string) {
	u.Created = created
	u.require(updateSubaccountResponseFieldCreated)
}

// SetModified sets the Modified field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetModified(modified string) {
	u.Modified = modified
	u.require(updateSubaccountResponseFieldModified)
}

// SetIsActive sets the IsActive field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetIsActive(isActive bool) {
	u.IsActive = isActive
	u.require(updateSubaccountResponseFieldIsActive)
}

// SetCreatedAt sets the CreatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetCreatedAt(createdAt string) {
	u.CreatedAt = createdAt
	u.require(updateSubaccountResponseFieldCreatedAt)
}

// SetUpdatedAt sets the UpdatedAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetUpdatedAt(updatedAt string) {
	u.UpdatedAt = updatedAt
	u.require(updateSubaccountResponseFieldUpdatedAt)
}

// SetLastUsed sets the LastUsed field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetLastUsed(lastUsed any) {
	u.LastUsed = lastUsed
	u.require(updateSubaccountResponseFieldLastUsed)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetAccount(account string) {
	u.Account = account
	u.require(updateSubaccountResponseFieldAccount)
}

// SetResourceURI sets the ResourceURI field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountResponse) SetResourceURI(resourceURI string) {
	u.ResourceURI = resourceURI
	u.require(updateSubaccountResponseFieldResourceURI)
}

func (u *UpdateSubaccountResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateSubaccountResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*u = UpdateSubaccountResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *u)
	if err != nil {
		return err
	}
	u.extraProperties = extraProperties
	u.rawJSON = json.RawMessage(data)
	return nil
}

func (u *UpdateSubaccountResponse) MarshalJSON() ([]byte, error) {
	type embed UpdateSubaccountResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (u *UpdateSubaccountResponse) String() string {
	if u == nil {
		return "<nil>"
	}
	if len(u.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(u.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

var (
	updateSubaccountRequestFieldAuthID    = big.NewInt(1 << 0)
	updateSubaccountRequestFieldSubAuthID = big.NewInt(1 << 1)
	updateSubaccountRequestFieldName      = big.NewInt(1 << 2)
	updateSubaccountRequestFieldEnabled   = big.NewInt(1 << 3)
	updateSubaccountRequestFieldKycMode   = big.NewInt(1 << 4)
)

type UpdateSubaccountRequest struct {
	// Your account Auth ID
	AuthID    string  `json:"-" url:"-"`
	SubAuthID string  `json:"-" url:"-"`
	Name      *string `json:"name,omitempty" url:"-"`
	Enabled   *bool   `json:"enabled,omitempty" url:"-"`
	// Change the verification mode. Promoting to `customer_use` requires the sub-account to have an `email`.
	KycMode *UpdateSubaccountRequestKycMode `json:"kyc_mode,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (u *UpdateSubaccountRequest) require(field *big.Int) {
	if u.explicitFields == nil {
		u.explicitFields = big.NewInt(0)
	}
	u.explicitFields.Or(u.explicitFields, field)
}

// SetAuthID sets the AuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountRequest) SetAuthID(authID string) {
	u.AuthID = authID
	u.require(updateSubaccountRequestFieldAuthID)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountRequest) SetSubAuthID(subAuthID string) {
	u.SubAuthID = subAuthID
	u.require(updateSubaccountRequestFieldSubAuthID)
}

// SetName sets the Name field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountRequest) SetName(name *string) {
	u.Name = name
	u.require(updateSubaccountRequestFieldName)
}

// SetEnabled sets the Enabled field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountRequest) SetEnabled(enabled *bool) {
	u.Enabled = enabled
	u.require(updateSubaccountRequestFieldEnabled)
}

// SetKycMode sets the KycMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (u *UpdateSubaccountRequest) SetKycMode(kycMode *UpdateSubaccountRequestKycMode) {
	u.KycMode = kycMode
	u.require(updateSubaccountRequestFieldKycMode)
}

func (u *UpdateSubaccountRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler UpdateSubaccountRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*u = UpdateSubaccountRequest(body)
	return nil
}

func (u *UpdateSubaccountRequest) MarshalJSON() ([]byte, error) {
	type embed UpdateSubaccountRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*u),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, u.explicitFields)
	return json.Marshal(explicitMarshaler)
}
