// Code generated by Fern. DO NOT EDIT.

package vobiz

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	big "math/big"
)

var (
	confirmSubaccountCinRequestFieldSubAuthID   = big.NewInt(1 << 0)
	confirmSubaccountCinRequestFieldCompanyName = big.NewInt(1 << 1)
	confirmSubaccountCinRequestFieldSelectedCin = big.NewInt(1 << 2)
)

type ConfirmSubaccountCinRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	CompanyName string `json:"company_name" url:"-"`
	SelectedCin string `json:"selected_cin" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *ConfirmSubaccountCinRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConfirmSubaccountCinRequest) SetSubAuthID(subAuthID string) {
	c.SubAuthID = subAuthID
	c.require(confirmSubaccountCinRequestFieldSubAuthID)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConfirmSubaccountCinRequest) SetCompanyName(companyName string) {
	c.CompanyName = companyName
	c.require(confirmSubaccountCinRequestFieldCompanyName)
}

// SetSelectedCin sets the SelectedCin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *ConfirmSubaccountCinRequest) SetSelectedCin(selectedCin string) {
	c.SelectedCin = selectedCin
	c.require(confirmSubaccountCinRequestFieldSelectedCin)
}

func (c *ConfirmSubaccountCinRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ConfirmSubaccountCinRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = ConfirmSubaccountCinRequest(body)
	return nil
}

func (c *ConfirmSubaccountCinRequest) MarshalJSON() ([]byte, error) {
	type embed ConfirmSubaccountCinRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createSubaccountKycSessionRequestFieldSubAuthID     = big.NewInt(1 << 0)
	createSubaccountKycSessionRequestFieldAccountAuthID = big.NewInt(1 << 1)
	createSubaccountKycSessionRequestFieldFlowType      = big.NewInt(1 << 2)
	createSubaccountKycSessionRequestFieldCustomerEmail = big.NewInt(1 << 3)
	createSubaccountKycSessionRequestFieldRedirectURL   = big.NewInt(1 << 4)
	createSubaccountKycSessionRequestFieldWebhookURL    = big.NewInt(1 << 5)
	createSubaccountKycSessionRequestFieldExpiresInDays = big.NewInt(1 << 6)
)

type CreateSubaccountKycSessionRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`
	// The sub-account's auth_id (typically equal to the path `sub_auth_id`).
	AccountAuthID string                                    `json:"account_auth_id" url:"-"`
	FlowType      CreateSubaccountKycSessionRequestFlowType `json:"flow_type" url:"-"`
	// Required when `flow_type` is `email`.
	CustomerEmail *string `json:"customer_email,omitempty" url:"-"`
	// Required when `flow_type` is `redirect`. After verification the customer's
	// browser is sent to this URL.
	RedirectURL *string `json:"redirect_url,omitempty" url:"-"`
	// HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent.
	WebhookURL    *string `json:"webhook_url,omitempty" url:"-"`
	ExpiresInDays *int    `json:"expires_in_days,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateSubaccountKycSessionRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetSubAuthID(subAuthID string) {
	c.SubAuthID = subAuthID
	c.require(createSubaccountKycSessionRequestFieldSubAuthID)
}

// SetAccountAuthID sets the AccountAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetAccountAuthID(accountAuthID string) {
	c.AccountAuthID = accountAuthID
	c.require(createSubaccountKycSessionRequestFieldAccountAuthID)
}

// SetFlowType sets the FlowType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetFlowType(flowType CreateSubaccountKycSessionRequestFlowType) {
	c.FlowType = flowType
	c.require(createSubaccountKycSessionRequestFieldFlowType)
}

// SetCustomerEmail sets the CustomerEmail field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetCustomerEmail(customerEmail *string) {
	c.CustomerEmail = customerEmail
	c.require(createSubaccountKycSessionRequestFieldCustomerEmail)
}

// SetRedirectURL sets the RedirectURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetRedirectURL(redirectURL *string) {
	c.RedirectURL = redirectURL
	c.require(createSubaccountKycSessionRequestFieldRedirectURL)
}

// SetWebhookURL sets the WebhookURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetWebhookURL(webhookURL *string) {
	c.WebhookURL = webhookURL
	c.require(createSubaccountKycSessionRequestFieldWebhookURL)
}

// SetExpiresInDays sets the ExpiresInDays field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateSubaccountKycSessionRequest) SetExpiresInDays(expiresInDays *int) {
	c.ExpiresInDays = expiresInDays
	c.require(createSubaccountKycSessionRequestFieldExpiresInDays)
}

func (c *CreateSubaccountKycSessionRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateSubaccountKycSessionRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateSubaccountKycSessionRequest(body)
	return nil
}

func (c *CreateSubaccountKycSessionRequest) MarshalJSON() ([]byte, error) {
	type embed CreateSubaccountKycSessionRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getSubaccountKycStatusRequestFieldSubAuthID = big.NewInt(1 << 0)
)

type GetSubaccountKycStatusRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetSubaccountKycStatusRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetSubaccountKycStatusRequest) SetSubAuthID(subAuthID string) {
	g.SubAuthID = subAuthID
	g.require(getSubaccountKycStatusRequestFieldSubAuthID)
}

var (
	searchSubaccountCinRequestFieldSubAuthID   = big.NewInt(1 << 0)
	searchSubaccountCinRequestFieldCompanyName = big.NewInt(1 << 1)
)

type SearchSubaccountCinRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	CompanyName string `json:"company_name" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SearchSubaccountCinRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchSubaccountCinRequest) SetSubAuthID(subAuthID string) {
	s.SubAuthID = subAuthID
	s.require(searchSubaccountCinRequestFieldSubAuthID)
}

// SetCompanyName sets the CompanyName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SearchSubaccountCinRequest) SetCompanyName(companyName string) {
	s.CompanyName = companyName
	s.require(searchSubaccountCinRequestFieldCompanyName)
}

func (s *SearchSubaccountCinRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SearchSubaccountCinRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SearchSubaccountCinRequest(body)
	return nil
}

func (s *SearchSubaccountCinRequest) MarshalJSON() ([]byte, error) {
	type embed SearchSubaccountCinRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	subaccountDigilockerInitiateRequestFieldSubAuthID   = big.NewInt(1 << 0)
	subaccountDigilockerInitiateRequestFieldRedirectURL = big.NewInt(1 << 1)
	subaccountDigilockerInitiateRequestFieldOauthState  = big.NewInt(1 << 2)
)

type SubaccountDigilockerInitiateRequest struct {
	// The sub-account's Auth ID.
	SubAuthID   string `json:"-" url:"-"`
	RedirectURL string `json:"redirect_url" url:"-"`
	// Opaque value echoed back on the redirect for CSRF protection.
	OauthState *string `json:"oauth_state,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SubaccountDigilockerInitiateRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerInitiateRequest) SetSubAuthID(subAuthID string) {
	s.SubAuthID = subAuthID
	s.require(subaccountDigilockerInitiateRequestFieldSubAuthID)
}

// SetRedirectURL sets the RedirectURL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerInitiateRequest) SetRedirectURL(redirectURL string) {
	s.RedirectURL = redirectURL
	s.require(subaccountDigilockerInitiateRequestFieldRedirectURL)
}

// SetOauthState sets the OauthState field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerInitiateRequest) SetOauthState(oauthState *string) {
	s.OauthState = oauthState
	s.require(subaccountDigilockerInitiateRequestFieldOauthState)
}

func (s *SubaccountDigilockerInitiateRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SubaccountDigilockerInitiateRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SubaccountDigilockerInitiateRequest(body)
	return nil
}

func (s *SubaccountDigilockerInitiateRequest) MarshalJSON() ([]byte, error) {
	type embed SubaccountDigilockerInitiateRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	subaccountDigilockerVerifyRequestFieldSubAuthID       = big.NewInt(1 << 0)
	subaccountDigilockerVerifyRequestFieldAccessRequestID = big.NewInt(1 << 1)
	subaccountDigilockerVerifyRequestFieldLinkedNumber    = big.NewInt(1 << 2)
)

type SubaccountDigilockerVerifyRequest struct {
	// The sub-account's Auth ID.
	SubAuthID       string `json:"-" url:"-"`
	AccessRequestID string `json:"access_request_id" url:"-"`
	// Optional. Binds the Aadhaar to a specific number (92-series).
	LinkedNumber *string `json:"linked_number,omitempty" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (s *SubaccountDigilockerVerifyRequest) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerVerifyRequest) SetSubAuthID(subAuthID string) {
	s.SubAuthID = subAuthID
	s.require(subaccountDigilockerVerifyRequestFieldSubAuthID)
}

// SetAccessRequestID sets the AccessRequestID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerVerifyRequest) SetAccessRequestID(accessRequestID string) {
	s.AccessRequestID = accessRequestID
	s.require(subaccountDigilockerVerifyRequestFieldAccessRequestID)
}

// SetLinkedNumber sets the LinkedNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubaccountDigilockerVerifyRequest) SetLinkedNumber(linkedNumber *string) {
	s.LinkedNumber = linkedNumber
	s.require(subaccountDigilockerVerifyRequestFieldLinkedNumber)
}

func (s *SubaccountDigilockerVerifyRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler SubaccountDigilockerVerifyRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*s = SubaccountDigilockerVerifyRequest(body)
	return nil
}

func (s *SubaccountDigilockerVerifyRequest) MarshalJSON() ([]byte, error) {
	type embed SubaccountDigilockerVerifyRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Aggregated KYC state for a sub-account.
var (
	subAccountKycStatusFieldSubAccountID    = big.NewInt(1 << 0)
	subAccountKycStatusFieldKycMode         = big.NewInt(1 << 1)
	subAccountKycStatusFieldBusinessType    = big.NewInt(1 << 2)
	subAccountKycStatusFieldOverallStatus   = big.NewInt(1 << 3)
	subAccountKycStatusFieldKycCallsBlocked = big.NewInt(1 << 4)
	subAccountKycStatusFieldVerifications   = big.NewInt(1 << 5)
)

type SubAccountKycStatus struct {
	SubAccountID  *string                           `json:"sub_account_id,omitempty" url:"sub_account_id,omitempty"`
	KycMode       *SubAccountKycStatusKycMode       `json:"kyc_mode,omitempty" url:"kyc_mode,omitempty"`
	BusinessType  *string                           `json:"business_type,omitempty" url:"business_type,omitempty"`
	OverallStatus *SubAccountKycStatusOverallStatus `json:"overall_status,omitempty" url:"overall_status,omitempty"`
	// True while the sub-account still needs KYC before it can place calls.
	KycCallsBlocked *bool `json:"kyc_calls_blocked,omitempty" url:"kyc_calls_blocked,omitempty"`
	// Per-document state keyed by verification type.
	Verifications map[string]SubAccountKycStatusVerificationsValue `json:"verifications,omitempty" url:"verifications,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (s *SubAccountKycStatus) GetSubAccountID() *string {
	if s == nil {
		return nil
	}
	return s.SubAccountID
}

func (s *SubAccountKycStatus) GetKycMode() *SubAccountKycStatusKycMode {
	if s == nil {
		return nil
	}
	return s.KycMode
}

func (s *SubAccountKycStatus) GetBusinessType() *string {
	if s == nil {
		return nil
	}
	return s.BusinessType
}

func (s *SubAccountKycStatus) GetOverallStatus() *SubAccountKycStatusOverallStatus {
	if s == nil {
		return nil
	}
	return s.OverallStatus
}

func (s *SubAccountKycStatus) GetKycCallsBlocked() *bool {
	if s == nil {
		return nil
	}
	return s.KycCallsBlocked
}

func (s *SubAccountKycStatus) GetVerifications() map[string]SubAccountKycStatusVerificationsValue {
	if s == nil {
		return nil
	}
	return s.Verifications
}

func (s *SubAccountKycStatus) GetExtraProperties() map[string]interface{} {
	if s == nil {
		return nil
	}
	return s.extraProperties
}

func (s *SubAccountKycStatus) require(field *big.Int) {
	if s.explicitFields == nil {
		s.explicitFields = big.NewInt(0)
	}
	s.explicitFields.Or(s.explicitFields, field)
}

// SetSubAccountID sets the SubAccountID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetSubAccountID(subAccountID *string) {
	s.SubAccountID = subAccountID
	s.require(subAccountKycStatusFieldSubAccountID)
}

// SetKycMode sets the KycMode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetKycMode(kycMode *SubAccountKycStatusKycMode) {
	s.KycMode = kycMode
	s.require(subAccountKycStatusFieldKycMode)
}

// SetBusinessType sets the BusinessType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetBusinessType(businessType *string) {
	s.BusinessType = businessType
	s.require(subAccountKycStatusFieldBusinessType)
}

// SetOverallStatus sets the OverallStatus field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetOverallStatus(overallStatus *SubAccountKycStatusOverallStatus) {
	s.OverallStatus = overallStatus
	s.require(subAccountKycStatusFieldOverallStatus)
}

// SetKycCallsBlocked sets the KycCallsBlocked field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetKycCallsBlocked(kycCallsBlocked *bool) {
	s.KycCallsBlocked = kycCallsBlocked
	s.require(subAccountKycStatusFieldKycCallsBlocked)
}

// SetVerifications sets the Verifications field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (s *SubAccountKycStatus) SetVerifications(verifications map[string]SubAccountKycStatusVerificationsValue) {
	s.Verifications = verifications
	s.require(subAccountKycStatusFieldVerifications)
}

func (s *SubAccountKycStatus) UnmarshalJSON(data []byte) error {
	type unmarshaler SubAccountKycStatus
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*s = SubAccountKycStatus(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *s)
	if err != nil {
		return err
	}
	s.extraProperties = extraProperties
	s.rawJSON = json.RawMessage(data)
	return nil
}

func (s *SubAccountKycStatus) MarshalJSON() ([]byte, error) {
	type embed SubAccountKycStatus
	var marshaler = struct {
		embed
	}{
		embed: embed(*s),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, s.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (s *SubAccountKycStatus) String() string {
	if s == nil {
		return "<nil>"
	}
	if len(s.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(s.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SubAccountKycStatusKycMode string

const (
	SubAccountKycStatusKycModePersonalUse SubAccountKycStatusKycMode = "personal_use"
	SubAccountKycStatusKycModeCustomerUse SubAccountKycStatusKycMode = "customer_use"
)

func NewSubAccountKycStatusKycModeFromString(s string) (SubAccountKycStatusKycMode, error) {
	switch s {
	case "personal_use":
		return SubAccountKycStatusKycModePersonalUse, nil
	case "customer_use":
		return SubAccountKycStatusKycModeCustomerUse, nil
	}
	var t SubAccountKycStatusKycMode
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SubAccountKycStatusKycMode) Ptr() *SubAccountKycStatusKycMode {
	return &s
}

type SubAccountKycStatusOverallStatus string

const (
	SubAccountKycStatusOverallStatusNotStarted SubAccountKycStatusOverallStatus = "not_started"
	SubAccountKycStatusOverallStatusPending    SubAccountKycStatusOverallStatus = "pending"
	SubAccountKycStatusOverallStatusVerified   SubAccountKycStatusOverallStatus = "verified"
	SubAccountKycStatusOverallStatusFailed     SubAccountKycStatusOverallStatus = "failed"
)

func NewSubAccountKycStatusOverallStatusFromString(s string) (SubAccountKycStatusOverallStatus, error) {
	switch s {
	case "not_started":
		return SubAccountKycStatusOverallStatusNotStarted, nil
	case "pending":
		return SubAccountKycStatusOverallStatusPending, nil
	case "verified":
		return SubAccountKycStatusOverallStatusVerified, nil
	case "failed":
		return SubAccountKycStatusOverallStatusFailed, nil
	}
	var t SubAccountKycStatusOverallStatus
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SubAccountKycStatusOverallStatus) Ptr() *SubAccountKycStatusOverallStatus {
	return &s
}

type SubAccountKycStatusVerificationsValue string

const (
	SubAccountKycStatusVerificationsValueNotStarted SubAccountKycStatusVerificationsValue = "not_started"
	SubAccountKycStatusVerificationsValuePending    SubAccountKycStatusVerificationsValue = "pending"
	SubAccountKycStatusVerificationsValueVerified   SubAccountKycStatusVerificationsValue = "verified"
	SubAccountKycStatusVerificationsValueFailed     SubAccountKycStatusVerificationsValue = "failed"
)

func NewSubAccountKycStatusVerificationsValueFromString(s string) (SubAccountKycStatusVerificationsValue, error) {
	switch s {
	case "not_started":
		return SubAccountKycStatusVerificationsValueNotStarted, nil
	case "pending":
		return SubAccountKycStatusVerificationsValuePending, nil
	case "verified":
		return SubAccountKycStatusVerificationsValueVerified, nil
	case "failed":
		return SubAccountKycStatusVerificationsValueFailed, nil
	}
	var t SubAccountKycStatusVerificationsValue
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (s SubAccountKycStatusVerificationsValue) Ptr() *SubAccountKycStatusVerificationsValue {
	return &s
}

type CreateSubaccountKycSessionRequestFlowType string

const (
	CreateSubaccountKycSessionRequestFlowTypeEmail    CreateSubaccountKycSessionRequestFlowType = "email"
	CreateSubaccountKycSessionRequestFlowTypeRedirect CreateSubaccountKycSessionRequestFlowType = "redirect"
)

func NewCreateSubaccountKycSessionRequestFlowTypeFromString(s string) (CreateSubaccountKycSessionRequestFlowType, error) {
	switch s {
	case "email":
		return CreateSubaccountKycSessionRequestFlowTypeEmail, nil
	case "redirect":
		return CreateSubaccountKycSessionRequestFlowTypeRedirect, nil
	}
	var t CreateSubaccountKycSessionRequestFlowType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateSubaccountKycSessionRequestFlowType) Ptr() *CreateSubaccountKycSessionRequestFlowType {
	return &c
}

var (
	verifySubaccountGstRequestFieldSubAuthID = big.NewInt(1 << 0)
	verifySubaccountGstRequestFieldGstin     = big.NewInt(1 << 1)
)

type VerifySubaccountGstRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`
	Gstin     string `json:"gstin" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VerifySubaccountGstRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifySubaccountGstRequest) SetSubAuthID(subAuthID string) {
	v.SubAuthID = subAuthID
	v.require(verifySubaccountGstRequestFieldSubAuthID)
}

// SetGstin sets the Gstin field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifySubaccountGstRequest) SetGstin(gstin string) {
	v.Gstin = gstin
	v.require(verifySubaccountGstRequestFieldGstin)
}

func (v *VerifySubaccountGstRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifySubaccountGstRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = VerifySubaccountGstRequest(body)
	return nil
}

func (v *VerifySubaccountGstRequest) MarshalJSON() ([]byte, error) {
	type embed VerifySubaccountGstRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	verifySubaccountPanRequestFieldSubAuthID = big.NewInt(1 << 0)
	verifySubaccountPanRequestFieldPan       = big.NewInt(1 << 1)
)

type VerifySubaccountPanRequest struct {
	// The sub-account's Auth ID.
	SubAuthID string `json:"-" url:"-"`
	Pan       string `json:"pan" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (v *VerifySubaccountPanRequest) require(field *big.Int) {
	if v.explicitFields == nil {
		v.explicitFields = big.NewInt(0)
	}
	v.explicitFields.Or(v.explicitFields, field)
}

// SetSubAuthID sets the SubAuthID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifySubaccountPanRequest) SetSubAuthID(subAuthID string) {
	v.SubAuthID = subAuthID
	v.require(verifySubaccountPanRequestFieldSubAuthID)
}

// SetPan sets the Pan field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (v *VerifySubaccountPanRequest) SetPan(pan string) {
	v.Pan = pan
	v.require(verifySubaccountPanRequestFieldPan)
}

func (v *VerifySubaccountPanRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler VerifySubaccountPanRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*v = VerifySubaccountPanRequest(body)
	return nil
}

func (v *VerifySubaccountPanRequest) MarshalJSON() ([]byte, error) {
	type embed VerifySubaccountPanRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*v),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, v.explicitFields)
	return json.Marshal(explicitMarshaler)
}
