// Code generated by Fern. DO NOT EDIT.

package account_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	client "github.com/vobiz-ai/Vobiz-Go-SDK/client"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAccountRetrieveAccountWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	_, invocationErr := client.Account.RetrieveAccount(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAccountRetrieveAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAccountRetrieveAccountWithWireMock", "GET", "/api/v1/auth/me", nil, 1)
}

func TestAccountGetConcurrencyWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &vobiz.GetConcurrencyRequest{
		AuthID: "MA_XXXXXX",
	}
	_, invocationErr := client.Account.GetConcurrency(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAccountGetConcurrencyWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAccountGetConcurrencyWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/concurrency", nil, 1)
}

func TestAccountPreviewChannelPricingWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &vobiz.PreviewChannelPricingRequest{
		AuthID:       "MA_XXXX",
		ResourceType: vobiz.CapacityResourceTypeConcurrentCalls,
		Quantity:     30,
	}
	_, invocationErr := client.Account.PreviewChannelPricing(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAccountPreviewChannelPricingWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAccountPreviewChannelPricingWithWireMock", "GET", "/api/v1/accounts/MA_XXXX/channel-pricing-preview", map[string]interface{}{"resource_type": "concurrent_calls", "quantity": "30"}, 1)
}

func TestAccountCreateChannelSubscriptionWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithBasicAuth("test-username", "test-password"),
	)
	request := &vobiz.ChannelSubscriptionRequest{
		AuthID:       "MA_XXXX",
		ResourceType: vobiz.CapacityResourceTypeConcurrentCalls,
		Quantity:     30,
	}
	_, invocationErr := client.Account.CreateChannelSubscription(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAccountCreateChannelSubscriptionWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAccountCreateChannelSubscriptionWithWireMock", "POST", "/api/v1/accounts/MA_XXXX/channel-subscriptions", nil, 1)
}
