// Code generated by Fern. DO NOT EDIT.

package subaccounts

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve all sub-accounts under the master account.
func (c *Client) ListSubaccounts(
	ctx context.Context,
	request *vobiz.ListSubaccountsRequest,
	opts ...option.RequestOption,
) (*vobiz.ListSubaccountsResponse, error) {
	response, err := c.WithRawResponse.ListSubaccounts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Create a new sub-account under the master account.
//
// Set `kyc_mode` to control how the sub-account is verified:
//
//   - `personal_use` *(default)* - the sub-account inherits the parent's
//     KYC; no separate verification is required.
//   - `customer_use` - the sub-account must complete its own KYC before it
//     can place calls. A fresh `customer_use` sub-account is returned with
//     `kyc_calls_blocked: true`. `customer_use` **requires** `email`.
func (c *Client) CreateSubaccount(
	ctx context.Context,
	request *vobiz.CreateSubaccountRequest,
	opts ...option.RequestOption,
) (*vobiz.CreateSubaccountResponse, error) {
	response, err := c.WithRawResponse.CreateSubaccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve details of a specific sub-account.
func (c *Client) RetrieveSubaccount(
	ctx context.Context,
	request *vobiz.RetrieveSubaccountRequest,
	opts ...option.RequestOption,
) (*vobiz.RetrieveSubaccountResponse, error) {
	response, err := c.WithRawResponse.RetrieveSubaccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update the name or status of a sub-account, or change its `kyc_mode`.
//
// Promoting an existing sub-account to `customer_use` requires the
// sub-account to already have an `email` (otherwise `400`). On any
// `kyc_mode` change, `kyc_calls_blocked` is re-derived from the
// sub-account's current KYC state.
func (c *Client) UpdateSubaccount(
	ctx context.Context,
	request *vobiz.UpdateSubaccountRequest,
	opts ...option.RequestOption,
) (*vobiz.UpdateSubaccountResponse, error) {
	response, err := c.WithRawResponse.UpdateSubaccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Permanently delete a sub-account and revoke its credentials.
func (c *Client) DeleteSubaccount(
	ctx context.Context,
	request *vobiz.DeleteSubaccountRequest,
	opts ...option.RequestOption,
) (*vobiz.DeleteSubaccountResponse, error) {
	response, err := c.WithRawResponse.DeleteSubaccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
