// Code generated by Fern. DO NOT EDIT.

package conferences

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve all active conference rooms on the account.
func (c *Client) ListConferences(
	ctx context.Context,
	request *vobiz.ListConferencesRequest,
	opts ...option.RequestOption,
) (*vobiz.ListConferencesResponse, error) {
	response, err := c.WithRawResponse.ListConferences(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Terminate all active conference rooms.
func (c *Client) DeleteAllConferences(
	ctx context.Context,
	request *vobiz.DeleteAllConferencesRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteAllConferences(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Get details and member list of a specific conference room.
func (c *Client) GetConference(
	ctx context.Context,
	request *vobiz.GetConferenceRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.GetConference(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Terminate a specific conference room and disconnect all members.
func (c *Client) DeleteConference(
	ctx context.Context,
	request *vobiz.DeleteConferenceRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.DeleteConference(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
