// Code generated by Fern. DO NOT EDIT.

package recordcalls

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Begin recording an active call. Set format, enable transcription, and configure a callback URL.
func (c *Client) StartRecording(
	ctx context.Context,
	request *vobiz.StartRecordingRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.StartRecording(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Stop an active recording on an in-progress call.
func (c *Client) StopRecording(
	ctx context.Context,
	request *vobiz.StopRecordingRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.StopRecording(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
