// Code generated by Fern. DO NOT EDIT.

package speaktext

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Convert text to speech and play it on a live call.
func (c *Client) Call(
	ctx context.Context,
	request *vobiz.SpeakTextCallRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.Call(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// Stop ongoing TTS playback on a live call.
func (c *Client) StopSpeakCall(
	ctx context.Context,
	request *vobiz.StopSpeakCallRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.StopSpeakCall(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
