// Code generated by Fern. DO NOT EDIT.

package account

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Retrieve complete account details including pricing tier and credentials.
func (c *Client) RetrieveAccount(
	ctx context.Context,
	opts ...option.RequestOption,
) (*vobiz.RetrieveAccountResponse, error) {
	response, err := c.WithRawResponse.RetrieveAccount(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve the current concurrent call usage and configured limits.
func (c *Client) GetConcurrency(
	ctx context.Context,
	request *vobiz.GetConcurrencyRequest,
	opts ...option.RequestOption,
) (*vobiz.GetConcurrencyResponse, error) {
	response, err := c.WithRawResponse.GetConcurrency(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
