// Code generated by Fern. DO NOT EDIT.

package endpoints_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	client "github.com/vobiz-ai/Vobiz-Go-SDK/client"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestEndpointsListEndpointsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.ListEndpointsRequest{
		AuthID: "MA_XXXXXX",
	}
	_, invocationErr := client.Endpoints.ListEndpoints(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEndpointsListEndpointsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEndpointsListEndpointsWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Endpoint/", nil, 1)
}

func TestEndpointsCreateEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.CreateEndpointRequest{
		AuthID:      "MA_XXXXXX",
		Username:    "john_doe",
		Password:    "SecurePassword123!",
		Alias:       "John's Desktop Phone",
		Application: 12345678,
	}
	_, invocationErr := client.Endpoints.CreateEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEndpointsCreateEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEndpointsCreateEndpointWithWireMock", "POST", "/api/v1/Account/MA_XXXXXX/Endpoint/", nil, 1)
}

func TestEndpointsRetrieveEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.RetrieveEndpointRequest{
		AuthID:     "MA_XXXXXX",
		EndpointID: "87654321",
	}
	_, invocationErr := client.Endpoints.RetrieveEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEndpointsRetrieveEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEndpointsRetrieveEndpointWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Endpoint/87654321/", nil, 1)
}

func TestEndpointsUpdateEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.UpdateEndpointRequest{
		AuthID:     "MA_XXXXXX",
		EndpointID: "87654321",
		Alias:      "John's Updated Desktop Phone",
		Password:   "NewSecurePassword456!",
	}
	_, invocationErr := client.Endpoints.UpdateEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEndpointsUpdateEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEndpointsUpdateEndpointWithWireMock", "POST", "/api/v1/Account/MA_XXXXXX/Endpoint/87654321/", nil, 1)
}

func TestEndpointsDeleteEndpointWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.DeleteEndpointRequest{
		AuthID:     "MA_XXXXXX",
		EndpointID: "87654321",
	}
	_, invocationErr := client.Endpoints.DeleteEndpoint(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestEndpointsDeleteEndpointWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestEndpointsDeleteEndpointWithWireMock", "DELETE", "/api/v1/Account/MA_XXXXXX/Endpoint/87654321/", nil, 1)
}
