// Code generated by Fern. DO NOT EDIT.

package originationuri

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Add an inbound SIP endpoint (origination URI) to a trunk.
func (c *Client) CreateOriginationURI(
	ctx context.Context,
	request *vobiz.CreateOriginationURIRequest,
	opts ...option.RequestOption,
) (*vobiz.CreateOriginationURIResponse, error) {
	response, err := c.WithRawResponse.CreateOriginationURI(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Retrieve all origination URIs on the account.
func (c *Client) ListOriginationURIs(
	ctx context.Context,
	request *vobiz.ListOriginationURIsRequest,
	opts ...option.RequestOption,
) (*vobiz.ListOriginationURIsResponse, error) {
	response, err := c.WithRawResponse.ListOriginationURIs(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Update an existing origination URI.
func (c *Client) UpdateOriginationURI(
	ctx context.Context,
	request *vobiz.UpdateOriginationURIRequest,
	opts ...option.RequestOption,
) (*vobiz.UpdateOriginationURIResponse, error) {
	response, err := c.WithRawResponse.UpdateOriginationURI(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Delete an origination URI from a trunk.
func (c *Client) DeleteOriginationURI(
	ctx context.Context,
	request *vobiz.DeleteOriginationURIRequest,
	opts ...option.RequestOption,
) (*string, error) {
	response, err := c.WithRawResponse.DeleteOriginationURI(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
