// Code generated by Fern. DO NOT EDIT.

package audio_streams_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	client "github.com/vobiz-ai/Vobiz-Go-SDK/client"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestAudioStreamsListStreamsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.ListStreamsRequest{
		AuthID:   "MA_XXXXXX",
		CallUUID: "call_uuid",
	}
	invocationErr := client.AudioStreams.ListStreams(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAudioStreamsListStreamsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAudioStreamsListStreamsWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Call/call_uuid/Stream/", nil, 1)
}

func TestAudioStreamsStartStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.StartStreamRequest{
		AuthID:     "MA_XXXXXX",
		CallUUID:   "call_uuid",
		ServiceURL: "wss://your-server.com/ws",
		Bidirectional: vobiz.Bool(
			true,
		),
		AudioTrack: vobiz.StartStreamRequestAudioTrackBoth.Ptr(),
	}
	_, invocationErr := client.AudioStreams.StartStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAudioStreamsStartStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAudioStreamsStartStreamWithWireMock", "POST", "/api/v1/Account/MA_XXXXXX/Call/call_uuid/Stream/", nil, 1)
}

func TestAudioStreamsGetStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.GetStreamRequest{
		AuthID:   "MA_XXXXXX",
		CallUUID: "call_uuid",
		StreamID: "stream_id",
	}
	invocationErr := client.AudioStreams.GetStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAudioStreamsGetStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAudioStreamsGetStreamWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Call/call_uuid/Stream/stream_id/", nil, 1)
}

func TestAudioStreamsStopStreamWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithToken("test-token"),
	)
	request := &vobiz.StopStreamRequest{
		AuthID:   "MA_XXXXXX",
		CallUUID: "call_uuid",
		StreamID: "stream_id",
	}
	invocationErr := client.AudioStreams.StopStream(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestAudioStreamsStopStreamWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestAudioStreamsStopStreamWithWireMock", "DELETE", "/api/v1/Account/MA_XXXXXX/Call/call_uuid/Stream/stream_id/", nil, 1)
}
