// Code generated by Fern. DO NOT EDIT.

package applications_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	http "net/http"
	os "os"
	testing "testing"

	require "github.com/stretchr/testify/require"
	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	client "github.com/vobiz-ai/Vobiz-Go-SDK/client"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]any,
	expected int,
) {
	wiremockURL := os.Getenv("WIREMOCK_URL")
	if wiremockURL == "" {
		wiremockURL = "http://localhost:8080"
	}
	WiremockAdminURL := wiremockURL + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			switch v := value.(type) {
			case string:
				reqBody.WriteString(`":{"equalTo":"`)
				reqBody.WriteString(v)
				reqBody.WriteString(`"}`)
			case []string:
				reqBody.WriteString(`":{"hasExactly":[`)
				for i, item := range v {
					if i > 0 {
						reqBody.WriteString(",")
					}
					reqBody.WriteString(`{"equalTo":"`)
					reqBody.WriteString(item)
					reqBody.WriteString(`"}`)
				}
				reqBody.WriteString(`]}`)
			}
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestApplicationsListApplicationsWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &vobiz.ListApplicationsRequest{
		AuthID: "MA_XXXXXX",
	}
	_, invocationErr := client.Applications.ListApplications(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplicationsListApplicationsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplicationsListApplicationsWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Application/", nil, 1)
}

func TestApplicationsCreateApplicationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &vobiz.CreateApplicationRequest{
		AuthID:       "MA_XXXXXX",
		AppName:      "My Voice Application",
		AnswerURL:    "https://example.com/answer",
		AnswerMethod: "POST",
	}
	_, invocationErr := client.Applications.CreateApplication(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplicationsCreateApplicationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplicationsCreateApplicationWithWireMock", "POST", "/api/v1/Account/MA_XXXXXX/Application/", nil, 1)
}

func TestApplicationsRetrieveApplicationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &vobiz.RetrieveApplicationRequest{
		AuthID: "MA_XXXXXX",
		AppID:  "12345678",
	}
	_, invocationErr := client.Applications.RetrieveApplication(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplicationsRetrieveApplicationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplicationsRetrieveApplicationWithWireMock", "GET", "/api/v1/Account/MA_XXXXXX/Application/12345678/", nil, 1)
}

func TestApplicationsUpdateApplicationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &vobiz.UpdateApplicationRequest{
		AuthID:           "MA_XXXXXX",
		AppID:            "12345678",
		AppName:          "Updated Application Name",
		DefaultNumberApp: true,
	}
	_, invocationErr := client.Applications.UpdateApplication(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplicationsUpdateApplicationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplicationsUpdateApplicationWithWireMock", "POST", "/api/v1/Account/MA_XXXXXX/Application/12345678/", nil, 1)
}

func TestApplicationsDeleteApplicationWithWireMock(
	t *testing.T,
) {
	WireMockBaseURL := os.Getenv("WIREMOCK_URL")
	if WireMockBaseURL == "" {
		WireMockBaseURL = "http://localhost:8080"
	}
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
		option.WithAPIKey("test-value"),
	)
	request := &vobiz.DeleteApplicationRequest{
		AuthID: "MA_XXXXXX",
		AppID:  "12345678",
	}
	_, invocationErr := client.Applications.DeleteApplication(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestApplicationsDeleteApplicationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestApplicationsDeleteApplicationWithWireMock", "DELETE", "/api/v1/Account/MA_XXXXXX/Application/12345678/", nil, 1)
}
