// Code generated by Fern. DO NOT EDIT.

// Endpoints that act on many records in one request. These accept the request, process it in the background, and deliver the result by email.
package bulkoperations
