// Code generated by Fern. DO NOT EDIT.

package conferencerecording

import (
	context "context"

	vobiz "github.com/vobiz-ai/Vobiz-Go-SDK"
	core "github.com/vobiz-ai/Vobiz-Go-SDK/core"
	internal "github.com/vobiz-ai/Vobiz-Go-SDK/internal"
	option "github.com/vobiz-ai/Vobiz-Go-SDK/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:         options.HTTPClient,
				MaxAttempts:    options.MaxAttempts,
				DisableRetries: options.DisableRetries,
			},
		),
	}
}

// Queue recording for all audio in a conference room. The response does not include a recording ID or download URL.
func (c *Client) StartConferenceRecording(
	ctx context.Context,
	request *vobiz.StartConferenceRecordingRequest,
	opts ...option.RequestOption,
) (any, error) {
	response, err := c.WithRawResponse.StartConferenceRecording(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Stop recording a conference room.
func (c *Client) StopConferenceRecording(
	ctx context.Context,
	request *vobiz.StopConferenceRecordingRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.StopConferenceRecording(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
